[package]
name = "mlpl-autograd"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
mlpl-core = { path = "../../components/lang-core/crates/mlpl-core" }
mlpl-array = { path = "../../components/lang-core/crates/mlpl-array" }
mlpl-array-ops-shape = { path = "../../components/lang-core/crates/mlpl-array-ops-shape" }
mlpl-array-ops-compose = { path = "../../components/lang-core/crates/mlpl-array-ops-compose" }
mlpl-array-ops-matmul = { path = "../../components/lang-core/crates/mlpl-array-ops-matmul" }
