//! Saga 33 step 001: language-model + tiny-MLP demos
//! extracted from `demos.rs`. Pure compile-time data.

use mlpl_web_demos_types::Demo;

/// Client-server demo (Phase 0/1, local-gpu-agentic): ask a local
/// Ollama model a question grounded in the REPL session. Connect
/// mode only -- on the public live demo this is visible but not
/// runnable. Capability: `requires_connect` (device cpu) via the
/// `DEMO_CAPABILITIES` table; the dropdown groups + disables it.
pub const ASK_OLLAMA_CONTEXTUAL: Demo = Demo {
    category: "Client-server",
    name: "Ask Ollama (contextual)",
    intro: "Ask a local Ollama model a question grounded in your sw-MLPL session. The server sends your question + a 'you are inside the sw-MLPL REPL' system prompt + your recent REPL activity to Ollama, so the answer is about MLPL specifically, not generic cloud trivia. Connect mode only (needs a running mlpl-serve); on the public demo this is visible but not runnable.",
    takeaway: "`:models ollama` lists the server's models; `:ask` routes your question through the server to Ollama with your REPL session context attached, so the answer is about your actual MLPL work, not generic trivia.",
    lines: &[
        ":models ollama",
        ":ask \"what does this REPL do, and what have I run so far?\"",
    ],
};

/// MLX (Apple GPU) demo: a TRUE-GPU LoRA fine-tune via `device("mlx")`
/// -- forward, backward, AND the Adam optimizer all run on the Apple
/// GPU (saga Phase 1b, step 010). The fine-tune step's loss is built as
/// an `mlx_rs`-traceable graph over the LoRA adapters and differentiated
/// with `value_and_grad`; an MLX-resident Adam updates the adapters
/// on-device. Connect mode + a Mac MLX peer only. Capability: mlx +
/// requires_connect, so it lands in its own MLX section.
pub const MLX_LORA_FINETUNE: Demo = Demo {
    category: "MLX (Apple GPU)",
    name: "MLX LoRA fine-tune",
    intro: "LoRA fine-tune a tiny language model entirely on the Apple GPU via MLX -- forward, backward, AND the Adam optimizer all run on-device (no CPU round-trip). Needs a connected mlpl-serve with a Mac MLX peer; not runnable on the public browser demo. Under device(\"mlx\"), the fine-tune step is traced by mlx_rs value_and_grad and the adapters are updated by an MLX-resident Adam, parity-tested against the CPU path within fp32 tolerance. Watch the fine-tune loss fall as the adapters learn.",
    takeaway: "device(\"mlx\") runs the whole fine-tune step on the GPU; lora() freezes the base and trains only the low-rank adapters, so the model specializes on a new corpus cheaply. Fine-tune loss drops from ~6 toward ~1.",
    lines: &[
        "corpus = load_preloaded(\"tiny_shakespeare_snippet\")  # base corpus",
        "tok    = train_bpe(corpus, 280, 0)                    # 280-token BPE",
        "ids    = apply_tokenizer(tok, corpus)",
        "X = reshape(shift_pairs_x(ids, 32), [reduce_mul(shape(shift_pairs_x(ids, 32)))])",
        "Y = reshape(shift_pairs_y(ids, 32), [reduce_mul(shape(shift_pairs_y(ids, 32)))])",
        "V = 280 ; d = 32 ; h = 1",
        "base = chain(embed(V, d, 0), residual(chain(rms_norm(d), causal_attention(d, h, 1))), rms_norm(d), linear(d, V, 4))  # tiny base LM",
        "experiment \"mlx_base\" { train 40 { adam(cross_entropy(apply(base, X), Y), base, 0.001, 0.9, 0.999, 0.00000001) } }  # pretrain the base",
        "student = lora(base, 8, 16.0, 0)                      # wrap with rank-8 LoRA, freeze the base",
        "device(\"mlx\") { experiment \"mlx_lora\" { train 40 { adam(cross_entropy(apply(student, X), Y), student, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(student, X), Y) } } }  # fine-tune adapters; fwd on GPU",
        "loss_curve(last_losses)                               # watch the fine-tune loss drop",
    ],
};

/// Connect-only CUDA demo (requires_connect, Device::Cuda via
/// `DEMO_CAPABILITIES`): the CUDA analog of `MLX_LORA_FINETUNE` -- the
/// same head-only-LoRA fine-tune, run on an NVIDIA GPU via candle.
pub const CUDA_LORA_FINETUNE: Demo = Demo {
    category: "CUDA (NVIDIA GPU)",
    name: "CUDA LoRA fine-tune",
    intro: "LoRA fine-tune a tiny language model on an NVIDIA GPU via CUDA -- forward, backward, AND the Adam optimizer all run on-device through candle autograd (no CPU round-trip). Needs a connected mlpl-serve with a Linux CUDA peer; not runnable on the public browser demo. Under device(\"cuda\"), the fine-tune step is one traceable candle graph differentiated by backward and the adapters are updated by a candle Adam, parity-tested against the CPU path within fp32 tolerance. Watch the fine-tune loss fall as the adapters learn.",
    takeaway: "device(\"cuda\") runs the whole fine-tune step on the GPU; lora() freezes the base and trains only the low-rank head adapters, so the model specializes on a new corpus cheaply. The CUDA loss curve matches the CPU path within fp32 tolerance.",
    lines: &[
        "ids = [1, 3, 5, 7, 2, 4, 6, 0, 9, 11, 13, 15, 2, 4, 6, 0]  # tiny token corpus",
        "X = reshape(shift_pairs_x(ids, 4), [reduce_mul(shape(shift_pairs_x(ids, 4)))])",
        "Y = reshape(shift_pairs_y(ids, 4), [reduce_mul(shape(shift_pairs_y(ids, 4)))])",
        "V = 16 ; d = 8 ; h = 1",
        "base = chain(embed(V, d, 0), residual(chain(rms_norm(d), causal_attention(d, h, 1))), rms_norm(d), linear(d, V, 2))  # head-only-LoRA demo arch",
        "experiment \"cuda_base\" { train 20 { adam(cross_entropy(apply(base, X), Y), base, 0.01, 0.9, 0.999, 0.00000001) } }  # pretrain the base",
        "student = lora(base, 2, 4.0, 7)                       # wrap with rank-2 LoRA, freeze the base",
        "device(\"cuda\") { experiment \"cuda_lora\" { train 30 { adam(cross_entropy(apply(student, X), Y), student, 0.05, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(student, X), Y) } } }  # full fine-tune step on the GPU",
        "loss_curve(last_losses)                               # watch the fine-tune loss drop",
    ],
};

/// Connect-only MLX demo (requires_connect, Device::Mlx via
/// `DEMO_CAPABILITIES`): the GPU fine-tune whose improvement is shown by
/// PLAYING, not by a loss curve. Lands in the MLX section.
pub const MLX_TICTACTOE_FINETUNE: Demo = Demo {
    category: "MLX (Apple GPU)",
    name: "MLX tic-tac-toe fine-tune",
    intro: "The whole game in MLPL -- no domain-specific builtins. We build the engine (winner as a matmul, alpha-beta minimax, board encoding), GENERATE the training set by self-play + minimax labels, LoRA-fine-tune a board -> move policy on the Apple GPU, and PROVE it learned by playing vs a random opponent before and after -- a red/gray/green waffle, not a loss curve. Needs a connected mlpl-serve with a Mac MLX peer (the self-play search + GPU fine-tune run server-side); not runnable on the public browser demo.",
    takeaway: "Winner detection is one matmul with an [8,9] line-incidence matrix; the optimal policy is a recursive alpha-beta minimax; the dataset is self-play (a while-loop accumulator). device(\"mlx\") runs the LoRA fine-tune on the GPU. The waffle's bottom band (after) has more green/gray and less red than the top (before): from no strategy toward a winning one, shown by playing.",
    lines: &[
        "lines_m = reshape([1,1,1,0,0,0,0,0,0, 0,0,0,1,1,1,0,0,0, 0,0,0,0,0,0,1,1,1, 1,0,0,1,0,0,1,0,0, 0,1,0,0,1,0,0,1,0, 0,0,1,0,0,1,0,0,1, 1,0,0,0,1,0,0,0,1, 0,0,1,0,1,0,1,0,0], [8, 9])  # the 8 lines",
        "def u:winner(board) { sums = reshape(matmul(lines_m, reshape(board, [9, 1])), [8]); if gt(reduce_add(eq(sums, 3), 0), 0) { 1 } else { if gt(reduce_add(eq(sums, -3), 0), 0) { -1 } else { 0 } } }  # winner = a matmul",
        "def u:terminal(board) { if gt(abs(u:winner(board)), 0) { 1 } else { eq(reduce_add(abs(board), 0), 9) } }",
        "def u:mx(a, b) { if gt(a, b) { a } else { b } }",
        "def u:mn(a, b) { if gt(a, b) { b } else { a } }",
        "def u:ge(a, b) { if gt(a, b) { 1 } else { eq(a, b) } }",
        "def u:ab(board, player, alpha, beta) { w = u:winner(board); if gt(abs(w), 0) { w } else { if eq(reduce_add(abs(board), 0), 9) { 0 } else { best = 0 - 2 * player; a = alpha; b = beta; done = 0; for c in iota(9) { if eq(take(board, 0, c), 0) { if eq(done, 0) { nb = board + player * eq(iota(9), c); s = u:ab(nb, 0 - player, a, b); if eq(player, 1) { best = u:mx(best, s); a = u:mx(a, best) } else { best = u:mn(best, s); b = u:mn(b, best) }; if u:ge(a, b) { done = 1 } else { 0 } } else { 0 } } else { 0 } }; best } } }  # alpha-beta minimax",
        "def u:best_move(board, player) { bv = 0 - 2 * player; bc = 0; seen = 0; for c in iota(9) { if eq(take(board, 0, c), 0) { nb = board + player * eq(iota(9), c); v = u:ab(nb, 0 - player, 0 - 2, 2); ti = if eq(seen, 0) { 1 } else { if eq(player, 1) { gt(v, bv) } else { gt(bv, v) } }; if ti { bv = v; bc = c; seen = 1 } else { 0 } } else { 0 } }; bc }  # the label oracle",
        "def u:encode(board, mover) { e = eq(board, 0); m = eq(board, mover); t = eq(board, 0 - mover); reshape(concat(concat(reshape(e, [9, 1]), reshape(m, [9, 1]), 1), reshape(t, [9, 1]), 1), [27]) }  # 27 one-hot features",
        "def u:rmove(board, s) { argmax(random(s, [9]) * eq(board, 0), 0) }  # random legal move",
        "def u:omove(board) { logits = reshape(apply(m, reshape(u:encode(board, 0 - 1), [1, 27])), [9]); argmax(logits + (eq(board, 0) - 1) * 1000, 0) }  # the model's move",
        "def u:play_o(n) { loss = 0; tie = 0; win = 0; g = 0; s = 90000; while gt(n, g) { board = fill([9], 0); player = 1; while eq(u:terminal(board), 0) { if eq(player, 1) { mv = u:rmove(board, s); s = s + 1 } else { mv = u:omove(board) }; board = board + player * eq(iota(9), mv); player = 0 - player }; w = u:winner(board); if eq(w, 1) { loss = loss + 1 } else { if eq(w, 0 - 1) { win = win + 1 } else { tie = tie + 1 } }; g = g + 1 }; reshape(concat(concat(reshape(loss, [1]), reshape(tie, [1]), 0), reshape(win, [1]), 0), [3]) }  # play vs random",
        "ng = 90 ; seed = 1 ; g = 0 ; started = 0 ; dx = fill([1, 27], 0) ; dy = fill([1, 1], 0)",
        "while gt(ng, g) { board = fill([9], 0); player = 1; while eq(u:terminal(board), 0) { if eq(player, 1) { mv = u:rmove(board, seed); seed = seed + 1 } else { bm = u:best_move(board, 0 - 1); xr = reshape(u:encode(board, 0 - 1), [1, 27]); yr = reshape(bm, [1, 1]); if eq(started, 0) { dx = xr; dy = yr; started = 1 } else { dx = concat(dx, xr, 0); dy = concat(dy, yr, 0) }; mv = bm }; board = board + player * eq(iota(9), mv); player = 0 - player }; g = g + 1 }  # on-policy self-play: X random, O optimal; collect O's positions + optimal move",
        "N = reshape(take(shape(dx), 0, 0), []) ; X = dx ; Y = reshape(dy, [N]) ; shape(X)",
        "base = chain(linear(27, 64, 0), relu_layer(), linear(64, 9, 1)) ; m = lora(base, 8, 16.0, 0)  # LoRA policy",
        "before = u:play_o(40)                                # untrained: [losses, ties, wins]",
        "device(\"mlx\") { experiment \"ttt\" { train 1800 { adam(cross_entropy(apply(m, X), Y), m, 0.05, 0.9, 0.999, 0.00000001) } } }  # fine-tune on the GPU",
        "after = u:play_o(40)                                 # trained: [losses, ties, wins]",
        "svg(reshape(concat(before, after), [2, 3]), \"waffle\")  # before (top) vs after (bottom)",
    ],
};

pub const TINY_LM_GENERATE: Demo = Demo {
    category: "Language Models",
    name: "Tiny LM Generate",
    intro: "End-to-end tiny transformer language model: tokenize a small corpus with BPE, wrap inputs as next-token pairs, build a 1-layer model (embed + causal_attention + rms_norm + linear head), train 30 [[Adam]] steps, then sample 20 tokens from a prompt and render the attention heatmap. The smallest program that trains and generates text.",
    takeaway: "A language model with a few thousand parameters produced a decoded string from a learned distribution and a [T,T] heatmap of what each position attended to. The loss curve should trend downward; the generated text is noisy because the model and budget are both tiny -- scale V, d, block, and step count for a serious run via the CLI.",
    lines: &[
        "corpus = load_preloaded(\"tiny_corpus\")                                                                                                                                                                                                                                                          # short pangram-style training corpus",
        "tok    = train_bpe(corpus, 260, 0)                                                                                                                                                                                                                                                                # train a 260-token BPE tokenizer",
        "ids    = apply_tokenizer(tok, corpus)                                                                                                                                                                                                                                                              # encode corpus -> integer ids",
        "X_all = shift_pairs_x(ids, 8)                                                                                                                                                                                                                                                                       # next-token input windows of length 8",
        "Y_all = shift_pairs_y(ids, 8)                                                                                                                                                                                                                                                                       # matching target windows shifted by 1",
        "X     = reshape(X_all, [reduce_mul(shape(X_all))])                                                                                                                                                                                                                                                  # flatten to 1-D for the embed lookup",
        "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])                                                                                                                                                                                                                                                  # flatten targets",
        "V = 260 ; d = 16 ; h = 1                                                                                                                                                                                                                                                                            # vocab / embed-dim / heads",
        "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))                                                                                                                                                                                                              # 1-layer transformer LM",
        "experiment \"tiny_lm_gen\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }  # train 30 Adam steps; record per-step loss",
        "loss_curve(last_losses)                                                                                                                                                                                                                                                                             # plot the training loss",
        "perplexity(apply(model, X), Y)                                                                                                                                                                                                                                                                       # exp(CE) -- canonical LM metric (lower is better)",
        "prompt = apply_tokenizer(tok, \"the \")                                                                                                                                                                                                                                                              # seed prompt as token ids",
        "seq    = prompt                                                                                                                                                                                                                                                                                      # generation buffer",
        "repeat 20 { logits = apply(model, seq); last = last_row(logits); nxt = sample(top_k(last, 20), 0.8, step); seq = concat(seq, nxt) }                                                                                                                                                                  # 20-token sample with top-k 20 + temperature 0.8",
        "decode(tok, seq)                                                                                                                                                                                                                                                                                     # decode ids back to text",
        "viz_ids = apply_tokenizer(tok, \"the quick\")                                                                                                                                                                                                                                                          # short input for the heatmap",
        "attn_w  = attention_weights(model, viz_ids)                                                                                                                                                                                                                                                          # extract the [T, T] attention weights",
        "svg(attn_w, \"heatmap\")                                                                                                                                                                                                                                                                              # what each position attended to",
    ],
};

pub const TINY_LM: Demo = Demo {
    category: "Language Models",
    name: "Tiny LM",
    intro: "Training-only variant of the Tiny LM: same model shape ([[Embedding]] + [[Attention]] (causal) + RMS norm + linear head, V=260, d=16, block=8), wrapped in [[experiment block (language keyword)]] so the final metric is logged, then plot the loss curve across 30 [[Adam]] steps. No generation -- just a clean 'does the loss go down' demo.",
    takeaway: "Loss curve trends downward over 30 steps; the [[experiment block (language keyword)]] registry records the run's final loss metric. For generation + attention visualization, see 'Tiny LM Generate'. For a serious run with V=280 and 200 steps, use the CLI: `mlpl-repl -f demos/tiny_lm.mlpl`.",
    lines: &[
        "corpus = load_preloaded(\"tiny_corpus\")                                                                                                                                                                                                                                                          # built-in pangram corpus",
        "tok    = train_bpe(corpus, 260, 0)                                                                                                                                                                                                                                                                # train a 260-token BPE tokenizer",
        "ids    = apply_tokenizer(tok, corpus)                                                                                                                                                                                                                                                              # encode the corpus to ids",
        "X_all = shift_pairs_x(ids, 8)                                                                                                                                                                                                                                                                       # next-token input windows of length 8",
        "Y_all = shift_pairs_y(ids, 8)                                                                                                                                                                                                                                                                       # matching target windows shifted by 1",
        "X     = reshape(X_all, [reduce_mul(shape(X_all))])                                                                                                                                                                                                                                                  # flatten to 1-D",
        "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])                                                                                                                                                                                                                                                  # flatten targets",
        "V = 260 ; d = 16 ; h = 1                                                                                                                                                                                                                                                                            # vocab / embed-dim / heads",
        "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))                                                                                                                                                                                                              # 1-layer transformer LM",
        "experiment \"tiny_lm\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }  # 30 Adam steps inside an experiment block",
        "loss_curve(last_losses)                                                                                                                                                                                                                                                                             # plot the training loss",
        "perplexity(apply(model, X), Y)                                                                                                                                                                                                                                                                       # exp(CE) -- the canonical LM metric, lower is better",
    ],
};

pub const TINY_MLP: Demo = Demo {
    category: "Language Models",
    name: "Tiny MLP",
    intro: "A hand-rolled 2-layer MLP on four blobs (two per class, XOR-ish layout). Forward + backward pass written out explicitly so every gradient is visible -- no autograd, no Model DSL. Ends with the decision-boundary render over a 30x30 grid.",
    takeaway: "You can see every matmul and every elementwise op in the training loop. For the same model with autograd hiding the backward pass, see 'Moons MLP'; for the same model as a Model DSL composition, see the tutorial's 'Model Composition' lesson.",
    lines: &[
        "D = blobs(3, 20, [[-2,-2],[2,2],[-2,2],[2,-2]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # 80 points in four blobs (XOR layout)",
        "X = matmul(D, [[1,0],[0,1],[0,0]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # drop the label column",
        "raw = reshape(matmul(D, [[0],[0],[1]]), [80])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # raw labels 0..3 (one per quadrant)",
        "y = gt(raw, 1.5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # binary label: half the quadrants are positive",
        "Y = one_hot(y, 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # one-hot for the loss",
        "W1 = randn(5, [2, 8]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # input -> hidden weights",
        "b1 = zeros([8])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden bias",
        "W2 = randn(6, [8, 2]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # hidden -> output weights",
        "b2 = zeros([2])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # output bias",
        "lr = 0.2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # learning rate",
        "repeat 600 { Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8])); H = tanh_fn(Z1); Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2])); P = softmax(Z2, 1); dZ2 = P - Y; gW2 = matmul(transpose(H), dZ2) / 80; gb2 = reduce_add(dZ2, 0) / 80; dH = matmul(dZ2, transpose(W2)); dZ1 = dH * (1 - H * H); gW1 = matmul(transpose(X), dZ1) / 80; gb1 = reduce_add(dZ1, 0) / 80; W1 = W1 - lr * gW1; b1 = b1 - lr * gb1; W2 = W2 - lr * gW2; b2 = b2 - lr * gb2 }  # 600 hand-rolled forward + backward steps; chain rule visible in dZ1 = dH * (1 - H*H)",
        "Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # final forward: hidden pre-activation",
        "H = tanh_fn(Z1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden activation",
        "Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # output pre-activation",
        "P = softmax(Z2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # row-wise probabilities",
        "mlp_pred = argmax(P, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # discrete class predictions",
        "mean(eq(mlp_pred, y))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # accuracy",
        "confusion_matrix(mlp_pred, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 2x2 prediction-vs-actual",
        "G = grid([-4, 4, -4, 4], 30)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 30x30 input-space grid",
        "GZ1 = matmul(G, W1) + matmul(ones([900, 1]), reshape(b1, [1, 8]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid forward: hidden pre-activation",
        "GH = tanh_fn(GZ1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid hidden activation",
        "GZ2 = matmul(GH, W2) + matmul(ones([900, 1]), reshape(b2, [1, 2]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid output pre-activation",
        "GP = softmax(GZ2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid probabilities",
        "p1 = reshape(matmul(GP, [[0],[1]]), [900])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # extract probability of class 1",
        "boundary_2d(p1, [30, 30], X, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # the decision surface that XOR needs",
    ],
};
