number = 6
slug = "move-runtime-dr"
status = "completed"
description = "Split step."
role = "production"
context_files = []
created_at = "2026-05-27T22:08:43"
completed_at = "2026-05-27T22:11:51"
task_type = "refactor"
commits = ["40524507f1d32754ee68bfe6b65d4803f9858185"]
