number = 2
slug = "002-run-and-load"
status = "completed"
description = """
Step 002: Run + Load.

Run button submits all non-empty non-comment lines fro..."""
role = "production"
context_files = []
created_at = "2026-05-26T12:11:16"
completed_at = "2026-05-26T12:24:41"
task_type = "feature"
commits = ["d285adc846d56a2bf04418ae456db6d54f4f66da"]
