pub struct Demo {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

pub const DEMOS: &[Demo] = &[
    Demo {
        name: "Basics",
        lines: &[
            "1 + 2",
            "3 * 4",
            "10 / 3",
            "[1, 2, 3] + [4, 5, 6]",
            "[1, 2, 3] * 10",
            "x = [10, 20, 30]",
            "y = x + 1",
            "y",
            "-[1, 2, 3]",
        ],
    },
    Demo {
        name: "Matrix Ops",
        lines: &[
            "x = iota(12)",
            "m = reshape(x, [3, 4])",
            "m",
            "transpose(m)",
            "shape(m)",
            "rank(m)",
            "reduce_add(m, 0)",
            "reduce_add(m, 1)",
        ],
    },
    Demo {
        name: "Math Functions",
        lines: &[
            "exp(0)",
            "exp([0, 1, 2])",
            "log(exp(1))",
            "sqrt([4, 9, 16, 25])",
            "abs([-3, 0, 5])",
            "pow([2, 3, 4], 2)",
            "sigmoid(0)",
            "sigmoid([-2, -1, 0, 1, 2])",
            "tanh_fn([-1, 0, 1])",
        ],
    },
    Demo {
        name: "Logistic Regression",
        lines: &[
            "X = [[0,0],[0,1],[1,0],[1,1]]",
            "y = [0, 0, 0, 1]",
            "w = zeros([2])",
            "b = 0",
            "lr = 1.0",
            "n = 4",
            "repeat 300 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
            "pred = sigmoid(matmul(X, reshape(w, [2, 1])) + b)",
            "rounded = gt(pred, 0.5)",
            "accuracy = mean(eq(reshape(rounded, [4]), y))",
            "accuracy",
            "svg(reshape(pred, [4]), \"bar\")",
            "ss = iota(16) / 10",
            "WS2 = matmul(reshape(ss, [16, 1]), reshape(w, [1, 2]))",
            "zs = matmul(WS2, transpose(X)) + matmul(reshape(ss * b, [16, 1]), ones([1, 4]))",
            "ps = sigmoid(zs)",
            "ys4 = matmul(ones([16, 1]), reshape(y, [1, 4]))",
            "losses = reduce_add((ps - ys4) * (ps - ys4), 1) / 4",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Loss Curve",
        lines: &[
            "x = [0, 1, 2, 3, 4]",
            "y = [0, 2, 4, 6, 8]",
            "ws = iota(25) / 4 - 1",
            "WS = reshape(ws, [25, 1])",
            "preds = matmul(WS, reshape(x, [1, 5]))",
            "YS = matmul(ones([25, 1]), reshape(y, [1, 5]))",
            "errs = preds - YS",
            "losses = reduce_add(errs * errs, 1) / 5",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Visualizations",
        lines: &[
            "svg([[0,0],[1,1],[2,4],[3,9],[4,16]], \"scatter\")",
            "svg([1, 3, 2, 5, 4, 6], \"line\")",
            "svg([3, 1, 4, 1, 5, 9, 2, 6], \"bar\")",
            "svg(reshape(iota(25), [5, 5]), \"heatmap\")",
        ],
    },
];
