//! Saga 33 step 001: classification / regression / clustering
//! demos extracted from `demos.rs`. Pure compile-time data.

use crate::demos::Demo;

pub const DECISION_BOUNDARY_LOGICAL_GATES: Demo = Demo {
    category: "Classification",
    name: "Decision Boundary: logical gates",
    intro: "Train the same 2-weight logistic regression on five 2-input boolean functions (AND, OR, NAND, NOR, XOR) and render the learned probability [[Decision boundary]] for each. Four of the five gates train to a clean linear boundary. The fifth -- XOR -- does not, because no straight line can separate the four XOR points. This is the canonical motivation for hidden layers and nonlinearity. To see XOR actually solved, load the 'Decision Boundary: XOR (with MLP)' demo next.",
    takeaway: "Linear classifiers can fit AND, OR, NAND, NOR perfectly because each of those functions has a single straight line that separates the positives from the negatives. XOR breaks that property -- its positives sit on one diagonal (0,1) and (1,0); its negatives on the other (0,0) and (1,1). No line passes between them. The XOR surface here stalls at a roughly-uniform 0.5 probability everywhere because the optimizer found the LEAST-bad linear fit, and the least-bad linear fit is to give up. The 'Decision Boundary: XOR (with MLP)' demo adds one hidden layer + [[Tanh]] and recovers a curved boundary that separates the points cleanly.",
    lines: &[
        "# Shared setup: 4-point boolean inputs, batch size, learning rate.",
        "# Each of the five parts below RE-USES this X with a different y",
        "# vector, RE-ZEROES w + b, and retrains from scratch.",
        "X = [[0,0],[0,1],[1,0],[1,1]]",
        "n = 4",
        "lr = 1.0",
        "# ============================================================",
        "# Part 1 of 5: AND.  y = [0, 0, 0, 1].  Only [1,1] is positive.",
        "# Linearly separable: any line that passes between [1,1] and",
        "# the other three points works. Expect a clean diagonal",
        "# boundary tilted toward [1,1].",
        "# ============================================================",
        "y = [0, 0, 0, 1]",
        "w = zeros([2])",
        "b = 0",
        "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
        "gx = grid([0, 1, 0, 1], 20)",
        "surface_and = reshape(sigmoid(reshape(matmul(gx, reshape(w, [2, 1])) + b, [400])), [20, 20])",
        "tp_and = [[0,0,0],[0,1,0],[1,0,0],[1,1,1]]",
        "svg(surface_and, \"decision_boundary\", tp_and)",
        "# ============================================================",
        "# Part 2 of 5: OR.  y = [0, 1, 1, 1].  Only [0,0] is negative.",
        "# Linearly separable. Expect a boundary tilted toward the origin.",
        "# ============================================================",
        "y = [0, 1, 1, 1]",
        "w = zeros([2])",
        "b = 0",
        "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
        "surface_or = reshape(sigmoid(reshape(matmul(gx, reshape(w, [2, 1])) + b, [400])), [20, 20])",
        "tp_or = [[0,0,0],[0,1,1],[1,0,1],[1,1,1]]",
        "svg(surface_or, \"decision_boundary\", tp_or)",
        "# ============================================================",
        "# Part 3 of 5: NAND.  y = [1, 1, 1, 0].  Inverse of AND.",
        "# Linearly separable. Boundary is the AND boundary with the",
        "# sign flipped -- everything OUTSIDE the [1,1] corner is positive.",
        "# ============================================================",
        "y = [1, 1, 1, 0]",
        "w = zeros([2])",
        "b = 0",
        "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
        "surface_nand = reshape(sigmoid(reshape(matmul(gx, reshape(w, [2, 1])) + b, [400])), [20, 20])",
        "tp_nand = [[0,0,1],[0,1,1],[1,0,1],[1,1,0]]",
        "svg(surface_nand, \"decision_boundary\", tp_nand)",
        "# ============================================================",
        "# Part 4 of 5: NOR.  y = [1, 0, 0, 0].  Inverse of OR.",
        "# Linearly separable. Boundary is the OR boundary flipped.",
        "# ============================================================",
        "y = [1, 0, 0, 0]",
        "w = zeros([2])",
        "b = 0",
        "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
        "surface_nor = reshape(sigmoid(reshape(matmul(gx, reshape(w, [2, 1])) + b, [400])), [20, 20])",
        "tp_nor = [[0,0,1],[0,1,0],[1,0,0],[1,1,0]]",
        "svg(surface_nor, \"decision_boundary\", tp_nor)",
        "# ============================================================",
        "# Part 5 of 5: XOR.  y = [0, 1, 1, 0].",
        "#",
        "# THIS PART CANNOT WORK with the linear classifier the four parts",
        "# above used.  XOR positives sit on one diagonal ([0,1] and [1,0]);",
        "# negatives on the other ([0,0] and [1,1]).  No straight line",
        "# separates the diagonals.  The training loop will still converge,",
        "# but it converges to the LEAST-bad linear fit -- roughly the",
        "# constant 0.5 surface.  Look for a near-uniform-color boundary",
        "# below and training-point colors that DO NOT match the surface",
        "# beneath them.  See the [[XOR (not linearly separable)]] glossary",
        "# entry for the full story.",
        "#",
        "# Working version: load \"Decision Boundary: XOR (with MLP)\" from",
        "# the demo dropdown after this one finishes -- a 2-layer MLP",
        "# (linear -> tanh -> linear) trained via adam recovers a curved",
        "# boundary that separates the four points cleanly.",
        "# ============================================================",
        "y = [0, 1, 1, 0]",
        "w = zeros([2])",
        "b = 0",
        "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
        "surface_xor = reshape(sigmoid(reshape(matmul(gx, reshape(w, [2, 1])) + b, [400])), [20, 20])",
        "tp_xor = [[0,0,0],[0,1,1],[1,0,1],[1,1,0]]",
        "svg(surface_xor, \"decision_boundary\", tp_xor)",
        "# Final w and b after the failed XOR fit.  Both near zero --",
        "# the model correctly figured out there's nothing useful a",
        "# single line can do here.",
        "w",
        "b",
    ],
};

pub const DECISION_BOUNDARY_XOR: Demo = Demo {
    category: "Classification",
    name: "Decision Boundary: XOR (with MLP)",
    intro: "Same XOR data as the 'Decision Boundary: logical gates' demo, but with a 2-layer MLP (linear -> tanh -> linear) trained via adam instead of a single linear layer trained via hand-rolled gradient descent. The hidden layer + nonlinearity is what turns XOR into a learnable problem. The decision_boundary render at the end shows the curved boundary the linear demo could not produce.",
    takeaway: "Two layers + a nonlinearity = a much more expressive class of functions. The hidden layer learns intermediate features (one neuron lights up on one diagonal, another on the other diagonal); the output layer combines those features into the XOR answer. The exact shape of the learned boundary depends on the random init seed; common patterns are a 'saddle' surface that pinches between the two positive points or an 'X' of red on the diagonal that contains [0,1] and [1,0]. Either way, the four training points sit on the correct side of the boundary -- something the linear demo's last svg() output could not achieve.",
    lines: &[
        "X = [[0,0],[0,1],[1,0],[1,1]]",
        "y = [0, 1, 1, 0]                              # XOR labels",
        "mdl = chain(linear(2, 4, 0), tanh_layer(), linear(4, 2, 1))",
        "# 500 adam steps. The forward pass apply(mdl, X) returns",
        "# 4x2 logits; cross_entropy reduces to the scalar loss.",
        "train 500 { adam(cross_entropy(apply(mdl, X), y), mdl, 0.1, 0.9, 0.999, 0.00000001); cross_entropy(apply(mdl, X), y) }",
        "loss_curve(last_losses)",
        "# Probe the trained model over a 20x20 grid of input points.",
        "gx = grid([0, 1, 0, 1], 20)",
        "logits = apply(mdl, gx)                       # [400, 2]",
        "probs = softmax(logits, 1)                    # row-stochastic",
        "# Slice out the positive-class probability column for the surface.",
        "pos = take(transpose(probs), 0, 1)            # column 1 -> [400]",
        "surface = reshape(pos, [20, 20])",
        "tp = [[0,0,0],[0,1,1],[1,0,1],[1,1,0]]        # XOR training points",
        "svg(surface, \"decision_boundary\", tp)",
        "# Final training accuracy: take argmax over each row of probs.",
        "train_logits = apply(mdl, X)",
        "train_probs = softmax(train_logits, 1)",
        "preds = argmax(train_probs, 1)",
        "correct = eq(preds, y)",
        "accuracy = reduce_add(correct) / 4",
        "accuracy",
    ],
};

pub const KMEANS: Demo = Demo {
    category: "Classification",
    name: "K-Means",
    intro: "K-means clustering without loops over points: all distances computed in one matmul, cluster assignments via argmax, and centroid updates via a one-hot-matrix-times-data trick. Three blobs in 2D, three centroids, ten iterations.",
    takeaway: "The final scatter shows points colored by their assigned cluster and the three centroids as a separate plot. Unsupervised -- no labels were passed in; the algorithm discovered the three groups from geometry alone.",
    lines: &[
        "D = blobs(7, 30, [[0, 0], [4, 4], [-4, 4]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 90 points across three blobs (with labels)",
        "X = matmul(D, [[1,0],[0,1],[0,0]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # drop the label column for unsupervised work",
        "C = [[1, 1], [3, 3], [-3, 3]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # 3 initial centroids",
        "repeat 10 { sqX = reshape(reduce_add(X*X, 1), [90, 1]); sqC = reshape(reduce_add(C*C, 1), [1, 3]); XC = matmul(X, transpose(C)); dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC; clus = argmax(-1 * dists, 1); jj = reshape(iota(3), [3, 1]); ll = reshape(clus, [1, 90]); diff = matmul(jj, ones([1, 90])) - matmul(ones([3, 1]), ll); A = eq(diff, 0); counts = reshape(reduce_add(A, 1), [3, 1]); sums = matmul(A, X); C = sums / matmul(counts, ones([1, 2])) }                                                                                                                                                                                              # 10 iterations of assign + update -- no per-point loop",
        "sqX = reshape(reduce_add(X*X, 1), [90, 1])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # per-point squared norms (final assignment)",
        "sqC = reshape(reduce_add(C*C, 1), [1, 3])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # per-centroid squared norms",
        "XC = matmul(X, transpose(C))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # cross-products",
        "dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # squared-distance matrix [90, 3]",
        "clus = argmax(-1 * dists, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # nearest centroid per point (argmax of negative distance)",
        "scatter_labeled(X, clus)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # points colored by cluster",
        "svg(C, \"scatter\")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # final centroid positions",
    ],
};

pub const LOGISTIC_REGRESSION: Demo = Demo {
    category: "Classification",
    name: "Logistic Regression",
    intro: "The hello-world of supervised learning: 2D AND with hand-rolled gradient descent, final-accuracy check, a bar chart of per-point predictions, and a 1D loss sweep along the weight direction showing the minimum the optimizer found.",
    takeaway: "Accuracy prints as 1.0; the bar chart shows confident [0, 0, 0, 1] predictions; the loss curve has a clean bowl shape. This is the sanity-check pattern every classifier should pass.",
    lines: &[
        "X = [[0,0],[0,1],[1,0],[1,1]]                                                                                                                                                                                                                                                                # AND truth-table inputs",
        "y = [0, 0, 0, 1]                                                                                                                                                                                                                                                                              # only [1,1] is positive",
        "w = zeros([2])                                                                                                                                                                                                                                                                                # 2-weight model",
        "b = 0                                                                                                                                                                                                                                                                                          # scalar bias",
        "lr = 1.0                                                                                                                                                                                                                                                                                       # learning rate",
        "n = 4                                                                                                                                                                                                                                                                                          # batch size",
        "repeat 300 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }  # 300 hand-rolled gradient-descent steps",
        "pred = sigmoid(matmul(X, reshape(w, [2, 1])) + b)                                                                                                                                                                                                                                              # final predictions",
        "rounded = gt(pred, 0.5)                                                                                                                                                                                                                                                                       # threshold to 0/1",
        "accuracy = mean(eq(reshape(rounded, [4]), y))                                                                                                                                                                                                                                                  # fraction correct",
        "accuracy                                                                                                                                                                                                                                                                                       # prints 1.0 when all four right",
        "svg(reshape(pred, [4]), \"bar\")                                                                                                                                                                                                                                                                # bar chart of per-point predictions",
        "ss = iota(16) / 10                                                                                                                                                                                                                                                                             # 16 scaling factors for the loss sweep",
        "WS2 = matmul(reshape(ss, [16, 1]), reshape(w, [1, 2]))                                                                                                                                                                                                                                         # 16 candidate weight vectors along w's direction",
        "zs = matmul(WS2, transpose(X)) + matmul(reshape(ss * b, [16, 1]), ones([1, 4]))                                                                                                                                                                                                                # logits at each scaling",
        "ps = sigmoid(zs)                                                                                                                                                                                                                                                                                # probabilities at each scaling",
        "ys4 = matmul(ones([16, 1]), reshape(y, [1, 4]))                                                                                                                                                                                                                                                 # broadcast labels across the 16 candidates",
        "losses = reduce_add((ps - ys4) * (ps - ys4), 1) / 4                                                                                                                                                                                                                                            # MSE at each scaling",
        "svg(losses, \"line\")                                                                                                                                                                                                                                                                          # 1D loss curve along the weight direction",
    ],
};

pub const MOONS_MLP: Demo = Demo {
    category: "Classification",
    name: "Moons MLP",
    intro: "A two-layer tanh MLP trained with [[Adam]] + cross-entropy on the 'two moons' synthetic dataset -- two interleaved half-circles that a single linear classifier can't separate. 200 training steps, then accuracy, a loss curve, a confusion matrix, and the learned decision boundary over a 30x30 grid.",
    takeaway: "A non-linear classifier with ~50 parameters separates the moons. cross_entropy(logits, y) is the canonical classification loss and is differentiable end-to-end through grad. The boundary SVG curves around each moon -- a visual proof that a hidden layer plus a non-linearity learned a non-linear decision surface.",
    lines: &[
        "M = moons(7, 120, 0.08)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # 120 points in two interleaved half-circles",
        "X = matmul(M, [[1,0],[0,1],[0,0]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # drop the label column",
        "y = reshape(matmul(M, [[0],[0],[1]]), [120])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # extract integer labels",
        "O120 = ones([120, 1])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # ones-column for bias broadcasting",
        "W1 = param[2, 8]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # input -> hidden weight matrix (declares trainable)",
        "b1 = param[1, 8]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden bias",
        "W2 = param[8, 2]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden -> output weights",
        "b2 = param[1, 2]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # output bias",
        "W1 = randn(11, [2, 8]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # initialize W1 with seeded normal",
        "W2 = randn(12, [8, 2]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # initialize W2 with seeded normal",
        "train 200 { adam(cross_entropy(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), y), [W1, b1, W2, b2], 0.05, 0.9, 0.999, 0.00000001); cross_entropy(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), y) }  # 200 Adam steps with cross-entropy loss",
        "Z1 = matmul(X, W1) + matmul(O120, b1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # forward: hidden pre-activation",
        "H = tanh_fn(Z1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden activation",
        "Z2 = matmul(H, W2) + matmul(O120, b2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # output pre-activation",
        "P = softmax(Z2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # row-wise probabilities",
        "pred = argmax(P, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # discrete class predictions",
        "accuracy = mean(eq(pred, y))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       # fraction correct",
        "accuracy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # prints close to 1.0",
        "loss_curve(last_losses)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # train block auto-captured per-step losses",
        "confusion_matrix(pred, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 2x2 prediction-vs-actual",
        "G = grid([-1.5, 2.5, -1, 1.5], 30)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # 30x30 grid in input space",
        "O900 = ones([900, 1])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # broadcast helper for grid bias",
        "GZ1 = matmul(G, W1) + matmul(O900, b1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # grid forward: hidden pre-activation",
        "GH = tanh_fn(GZ1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid hidden activation",
        "GZ2 = matmul(GH, W2) + matmul(O900, b2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # grid output pre-activation",
        "GP = softmax(GZ2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # grid probabilities",
        "p1 = reshape(matmul(GP, [[0],[1]]), [900])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # extract probability of class 1",
        "boundary_2d(p1, [30, 30], X, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # render the curved decision surface",
    ],
};

pub const PCA: Demo = Demo {
    category: "Classification",
    name: "PCA",
    intro: "Principal Component Analysis without calling into a library: make anisotropic 2D data, center it, form the covariance matrix, run [[power iteration]] to find the top eigenvector, and project every point onto it. The top axis is the direction of maximum variance.",
    takeaway: "The scatter is colored by which side of zero each point's projection lands on; the line shows the found principal axis. Power iteration converges in ~10 steps to a direction that's clearly the long axis of the data cloud.",
    lines: &[
        "Xraw = randn(1, [60, 2])                                          # 60 points of isotropic 2D noise",
        "X = matmul(Xraw, [[1, 2], [0, 0.3]])                              # stretch into an anisotropic cloud",
        "cm = reduce_add(X, 0) / 60                                        # column means -- the centroid",
        "Xc = X - matmul(ones([60, 1]), reshape(cm, [1, 2]))               # center the data",
        "Cov = matmul(transpose(Xc), Xc) / 60                              # 2x2 covariance matrix",
        "v = [1, 0]                                                         # initial guess for the top eigenvector",
        "repeat 10 { v = matmul(Cov, v); v = v / sqrt(dot(v, v)) }         # power iteration: 10 multiplies + normalize",
        "coords = reshape(matmul(Xc, reshape(v, [2, 1])), [60])            # project each point onto the principal axis",
        "labels = gt(coords, 0)                                             # which side of the axis each point lands on",
        "ends = matmul(reshape([-3, 3], [2, 1]), reshape(v, [1, 2]))       # endpoints of the axis line in centered space",
        "line = ends + matmul(ones([2, 1]), reshape(cm, [1, 2]))           # shift the line back into original space",
        "scatter_labeled(X, labels)                                         # data colored by side of the principal axis",
        "svg(line, \"line\")                                                 # the principal axis itself",
    ],
};

pub const SOFTMAX_CLASSIFIER: Demo = Demo {
    category: "Classification",
    name: "Softmax Classifier",
    intro: "Three-class classification on 90 blob points. softmax + cross-entropy gradient descent (done in closed form here -- P - Y IS the gradient through the softmax+CE pair), then the usual accuracy / confusion-matrix / decision-boundary close.",
    takeaway: "A single linear layer with three output heads separates three well-spaced clusters. The decision boundary shows three roughly-wedge-shaped regions, one per class.",
    lines: &[
        "D = blobs(11, 30, [[0, 0], [4, 4], [-4, 4]])                                                                                                                                                                                                                                                  # 90 points in three blobs",
        "X = matmul(D, [[1,0],[0,1],[0,0]])                                                                                                                                                                                                                                                            # drop the label column",
        "tl = reshape(matmul(D, [[0],[0],[1]]), [90])                                                                                                                                                                                                                                                  # integer labels (length 90)",
        "Y = one_hot(tl, 3)                                                                                                                                                                                                                                                                            # one-hot targets [90, 3]",
        "W = zeros([2, 3])                                                                                                                                                                                                                                                                              # 2-input, 3-class weight matrix",
        "b = zeros([3])                                                                                                                                                                                                                                                                                  # per-class bias",
        "lr = 0.2                                                                                                                                                                                                                                                                                       # learning rate",
        "repeat 300 { logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3])); P = softmax(logits, 1); dZ = P - Y; gW = matmul(transpose(X), dZ) / 90; gb = reduce_add(dZ, 0) / 90; W = W - lr * gW; b = b - lr * gb }  # 300 closed-form gradient steps (P-Y is the softmax+CE gradient)",
        "logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3]))                                                                                                                                                                                                                              # final logits",
        "P = softmax(logits, 1)                                                                                                                                                                                                                                                                          # final probabilities",
        "pred = argmax(P, 1)                                                                                                                                                                                                                                                                             # class predictions",
        "accuracy = mean(eq(pred, tl))                                                                                                                                                                                                                                                                   # fraction correct",
        "accuracy                                                                                                                                                                                                                                                                                        # prints close to 1.0",
        "confusion_matrix(pred, tl)                                                                                                                                                                                                                                                                      # 3x3 prediction-vs-actual",
        "G = grid([-6, 6, -3, 6], 30)                                                                                                                                                                                                                                                                   # 30x30 grid in input space",
        "gl = matmul(G, W) + matmul(ones([900, 1]), reshape(b, [1, 3]))                                                                                                                                                                                                                                 # logits over the grid",
        "gP = softmax(gl, 1)                                                                                                                                                                                                                                                                             # per-grid-cell class probabilities",
        "p0 = reshape(matmul(gP, [[1],[0],[0]]), [900])                                                                                                                                                                                                                                                  # extract probability of class 0",
        "boundary_2d(p0, [30, 30], X, tl)                                                                                                                                                                                                                                                                # three-wedge decision surface",
    ],
};
