//! Saga 33 step 001: attention / transformer building-block
//! demos extracted from `demos.rs`. Pure compile-time data.

use crate::demos::Demo;

pub const ATTENTION_PATTERN: Demo = Demo {
    name: "Attention Pattern",
    intro: "The scaled-dot-product attention formula from '[[Attention]] is All You Need', spelled out. Two Q and K matrices, scored and softmax'd, rendered as heatmaps. A second self-attention pass (Q attending to itself) shows the diagonal pattern that makes self-attention recognizable on sight.",
    takeaway: "You just built transformer attention in four lines: matmul + transpose + softmax. The heatmaps show where each query row puts probability mass -- self-attention concentrates on the diagonal; cross-attention doesn't.",
    lines: &[
        "Q = randn(17, [6, 4])                              # 6 queries, 4 dims each",
        "K = randn(23, [6, 4])                              # 6 keys (different seed = cross-attention)",
        "scores = matmul(Q, transpose(K)) / sqrt(4)         # scaled dot-product",
        "A = softmax(scores, 1)                             # row-wise probability over keys",
        "svg(scores, \"heatmap\")                            # raw scores (signed values)",
        "svg(A, \"heatmap\")                                 # attention weights (rows sum to 1)",
        "Qs = randn(17, [6, 4])                             # reuse the same matrix as both Q and K ...",
        "Sself = matmul(Qs, transpose(Qs)) / sqrt(4)        # ... and you have self-attention",
        "Aself = softmax(Sself, 1)                          # row-wise softmax",
        "svg(Aself, \"heatmap\")                             # diagonal-dominant: the self-attention signature",
    ],
};

pub const SELF_ATTENTION_FROM_SCRATCH: Demo = Demo {
    name: "Self-Attention from Scratch",
    intro: "Build one head of self-attention from primitives, no `attention()` layer involved. Three projection matrices Wq / Wk / Wv turn the input X into Q, K, V; then `softmax(Q K^T / sqrt(d_k)) V` mixes the values according to which keys each query attended to. Tiny T=6, d=4 toy input so every intermediate matrix renders cleanly.",
    takeaway: "[[Self-attention]] is four matmuls, one transpose, one scalar division, one softmax. The score heatmap is what a query is asking; the weight heatmap is what it gets back; the output is the weighted V. With random projections the pattern is noise -- training is what makes the weights specialize on a task.",
    lines: &[
        "T = 6                                                # 6 tokens in the sequence",
        "d_model = 4                                          # each token is a 4-dim vector",
        "X : [seq, d] = randn(0, [T, d_model])                # the input: a [6, 4] block of random embeddings",
        "Wq = randn(1, [d_model, d_model])                    # query projection (learned in a real model)",
        "Wk = randn(2, [d_model, d_model])                    # key projection",
        "Wv = randn(3, [d_model, d_model])                    # value projection",
        "Q = matmul(X, Wq)                                    # what each token is asking about",
        "K = matmul(X, Wk)                                    # what each token advertises about itself",
        "V = matmul(X, Wv)                                    # what each token shares if attended-to",
        "scores = matmul(Q, transpose(K)) / sqrt(d_model)     # raw query-key similarity, scaled so softmax stays stable",
        "svg(scores, \"heatmap\")                               # visualize the unnormalized scores",
        "weights = softmax(scores, 1)                         # each row becomes a probability distribution over keys",
        "svg(weights, \"heatmap\")                              # visualize the attention pattern",
        "out = matmul(weights, V)                             # weighted average of value vectors per query",
        "shape(out)                                           # same shape as the input: [T, d_model]",
    ],
};

pub const MULTI_HEAD_ATTENTION_FROM_SCRATCH: Demo = Demo {
    name: "Multi-Head Attention from Scratch",
    intro: "[[Multi-head attention]] from primitives. Each head gets a slab of the d_model channels via a column-selector matrix S_h: [d_model, d_k], runs scaled-dot-product attention on its own Q/K/V slabs, and writes back into the full-width output via S_h^T. Tiny T=4, d_model=4, heads=2 (so d_k=2) keeps every per-head [T, T] heatmap interpretable.",
    takeaway: "Two heads, two different attention patterns. Each head sees only its slab of d_model, so it can specialize. Real `attention(d, heads, seed)` does the slicing in Rust without materializing selector matrices, and adds a final Wo projection -- but the math is the same: per-head softmax(Q K^T / sqrt(d_k)) V, concat, project.",
    lines: &[
        "T = 4                                                # 4 tokens",
        "d_model = 4                                          # 4-dim vectors total ...",
        "heads = 2                                            # ... split into 2 heads ...",
        "d_k = d_model / heads                                # ... each head is 2 dims wide",
        "X : [seq, d] = randn(0, [T, d_model])                # the input: [T, d_model]",
        "Wq = randn(1, [d_model, d_model])                    # full-width Q projection",
        "Wk = randn(2, [d_model, d_model])                    # full-width K projection",
        "Wv = randn(3, [d_model, d_model])                    # full-width V projection",
        "S0 = [[1,0],[0,1],[0,0],[0,0]]                       # selector for head 0: picks columns 0..d_k",
        "S1 = [[0,0],[0,0],[1,0],[0,1]]                       # selector for head 1: picks columns d_k..d_model",
        "Q = matmul(X, Wq)                                    # full-width Q for all heads",
        "K = matmul(X, Wk)                                    # full-width K",
        "V = matmul(X, Wv)                                    # full-width V",
        "Q0 = matmul(Q, S0)                                   # head-0 slab of Q (T, d_k)",
        "K0 = matmul(K, S0)                                   # head-0 slab of K",
        "V0 = matmul(V, S0)                                   # head-0 slab of V",
        "W0 = softmax(matmul(Q0, transpose(K0)) / sqrt(d_k), 1) # head-0 attention weights",
        "svg(W0, \"heatmap\")                                   # head-0 pattern",
        "out0 = matmul(W0, V0)                                # head-0 output slab",
        "Q1 = matmul(Q, S1)                                   # head-1 slab of Q",
        "K1 = matmul(K, S1)                                   # head-1 slab of K",
        "V1 = matmul(V, S1)                                   # head-1 slab of V",
        "W1 = softmax(matmul(Q1, transpose(K1)) / sqrt(d_k), 1) # head-1 attention weights",
        "svg(W1, \"heatmap\")                                   # head-1 pattern (different from head-0)",
        "out1 = matmul(W1, V1)                                # head-1 output slab",
        "out_concat = matmul(out0, transpose(S0)) + matmul(out1, transpose(S1)) # scatter slabs back into [T, d_model] and sum",
        "Wo = randn(7, [d_model, d_model])                    # final output projection (mixes across heads)",
        "final_out = matmul(out_concat, Wo)                   # the multi-head output",
        "shape(final_out)                                     # back to [T, d_model]",
    ],
};

pub const CROSS_ATTENTION_FROM_SCRATCH: Demo = Demo {
    name: "Cross-Attention from Scratch",
    intro: "[[Cross-attention]] is the same `softmax(Q K^T / sqrt(d_k)) V` as self-attention, but Q comes from a target sequence (T_tgt=4) and K, V come from a separate source sequence (T_src=6). The weight matrix is `[T_tgt, T_src]` -- non-square -- which is the visual signature: each target query distributes its attention across all source positions, not over its own sequence.",
    takeaway: "The non-square weight heatmap (4 rows, 6 cols) is the giveaway: target queries are looking at source content, not at themselves. The output is `[T_tgt, d_model]` -- same shape as the target input -- but its values are mixtures of the source's V vectors weighted by query-key similarity. Stack one cross-attention block after a causal-self-attention block and you have a transformer decoder layer.",
    lines: &[
        "T_tgt = 4                                            # target sequence length (decoder side)",
        "T_src = 6                                            # source sequence length (encoder side)",
        "d_model = 4                                          # shared embedding width",
        "X_tgt : [seq, d] = randn(0, [T_tgt, d_model])        # target tokens",
        "X_src : [seq, d] = randn(1, [T_src, d_model])        # source tokens (in a real pipeline, encoder output)",
        "Wq = randn(2, [d_model, d_model])                    # Q projection (target side)",
        "Wk = randn(3, [d_model, d_model])                    # K projection (source side)",
        "Wv = randn(4, [d_model, d_model])                    # V projection (source side)",
        "Q = matmul(X_tgt, Wq)                                # queries from target",
        "K = matmul(X_src, Wk)                                # keys from source",
        "V = matmul(X_src, Wv)                                # values from source",
        "scores = matmul(Q, transpose(K)) / sqrt(d_model)     # [T_tgt, T_src] -- non-square: cross-attn signature",
        "weights = softmax(scores, 1)                         # each target row distributes over source positions",
        "shape(weights)                                       # [T_tgt, T_src] -- not [T, T]",
        "svg(weights, \"heatmap\")                              # the non-square pattern is the giveaway",
        "out = matmul(weights, V)                             # mix source values per target query",
        "shape(out)                                           # back to target shape: [T_tgt, d_model]",
    ],
};

pub const ENCODER_BLOCK: Demo = Demo {
    name: "Encoder Block",
    intro: "One transformer encoder block built from the model DSL: pre-norm self-attention with a residual, then pre-norm feedforward (linear -> relu -> linear) with another residual. Same shape in, same shape out. The residual connections let gradients flow past the attention and FFN layers; the pre-norm `rms_norm` keeps activations stable.",
    takeaway: "An encoder block is just chain(residual(self-attn), residual(ffn)). Stack a dozen of these and you have [[BERT]]; add cross-attention and a causal mask and you have a decoder block. The attention heatmap shows what each position is attending to in this single layer; deep encoders compose these patterns into hierarchical representations.",
    lines: &[
        "X = randn(0, [4, 8])                                                                                                                                                # 4 tokens of dim 8",
        "encoder = chain(residual(chain(rms_norm(8), attention(8, 1, 1))), residual(chain(rms_norm(8), linear(8, 16, 2), relu_layer(), linear(16, 8, 3))))  # pre-norm self-attn + residual; pre-norm FFN + residual",
        "out = apply(encoder, X)                                                                                                                                            # forward pass through both sub-blocks",
        "shape(out)                                                                                                                                                          # same shape in, same shape out",
        "bare_attn = attention(8, 1, 1)                                                                                                                                      # standalone layer for the attention_weights extractor",
        "svg(attention_weights(bare_attn, X), \"heatmap\")                                                                                                                    # render the [T, T] attention pattern",
    ],
};

pub const DECODER_BLOCK: Demo = Demo {
    name: "Decoder Block",
    intro: "One transformer decoder block: three sub-blocks instead of two. Causal self-attention (target attends only to past target tokens), then cross-attention (target queries attend to encoder output -- built from scratch since MLPL has no cross-attention layer primitive), then a feedforward sub-block. X_tgt is the target sequence (T=4); X_src stands in for the encoder's output (T=6) -- a real pipeline would feed the encoder demo's `out` here.",
    takeaway: "A decoder block is encoder-block + cross-attention. The cross-attention heatmap is non-square ([T_tgt, T_src]): target queries distributing attention over encoder positions. Stack a dozen of these and you have [[GPT]] (decoder-only, drop the cross-attn step) or T5 (encoder-decoder, keep all three).",
    lines: &[
        "T_tgt = 4                                                                                # target sequence length",
        "T_src = 6                                                                                # source sequence length (encoder output stand-in)",
        "d_model = 8                                                                              # shared embedding width",
        "d_ff = 16                                                                                # FFN hidden width",
        "X_tgt = randn(0, [T_tgt, d_model])                                                       # target tokens",
        "X_src = randn(1, [T_src, d_model])                                                       # source tokens",
        "self_attn = residual(chain(rms_norm(d_model), causal_attention(d_model, 1, 2)))         # sub-block 1: causal self-attn + residual",
        "H = apply(self_attn, X_tgt)                                                              # target after self-attention",
        "pre_xattn = rms_norm(d_model)                                                            # cross-attn pre-norm layer",
        "H_norm = apply(pre_xattn, H)                                                             # normalized H for cross-attn queries",
        "Wq = randn(3, [d_model, d_model])                                                        # cross-attn Q (target side)",
        "Wk = randn(4, [d_model, d_model])                                                        # cross-attn K (source side)",
        "Wv = randn(5, [d_model, d_model])                                                        # cross-attn V (source side)",
        "Q = matmul(H_norm, Wq)                                                                   # queries from target",
        "K = matmul(X_src, Wk)                                                                    # keys from source",
        "V = matmul(X_src, Wv)                                                                    # values from source",
        "weights = softmax(matmul(Q, transpose(K)) / sqrt(d_model), 1)                            # cross-attention weights [T_tgt, T_src]",
        "shape(weights)                                                                           # confirm non-square",
        "svg(weights, \"heatmap\")                                                                  # the cross-attn pattern",
        "H2 = H + matmul(weights, V)                                                              # residual: H + cross-attn output",
        "ffn = residual(chain(rms_norm(d_model), linear(d_model, d_ff, 6), relu_layer(), linear(d_ff, d_model, 7)))  # sub-block 3: pre-norm FFN + residual",
        "out = apply(ffn, H2)                                                                     # final decoder block output",
        "shape(out)                                                                               # same shape as X_tgt",
    ],
};
