pub struct Demo {
    pub name: &'static str,
    /// One-to-three-sentence framing shown before the demo runs:
    /// what the demo does and why. Intentionally short -- the
    /// code is the real lesson.
    pub intro: &'static str,
    /// One-to-three-sentence takeaway shown after the demo's last
    /// line completes: what the output proves and where to go
    /// next. Paired with `intro` to bookend the run.
    pub takeaway: &'static str,
    pub lines: &'static [&'static str],
}

// Demos are listed alphabetically by `name`.
pub const DEMOS: &[Demo] = &[
    Demo {
        name: "Analysis Helpers",
        intro: "Tour of the high-level viz helpers: histogram, labeled scatter, loss curve, confusion matrix, and a 2D decision-boundary surface. Each returns an SVG that renders inline. Use these as building blocks when you want one line of code to answer one question about your data or model.",
        takeaway: "Six one-liners, six labeled plots. Every helper under 'analysis' in the docs takes arrays you already have and returns an SVG -- no separate plotting library, no config blocks.",
        lines: &[
            "hist([1, 2, 2, 3, 3, 3, 4, 4, 5], 5)",
            "scatter_labeled([[0,0],[1,1],[0,1],[1,0]], [0, 0, 1, 1])",
            "loss_curve([5, 3, 2, 1.5, 1.0, 0.7, 0.5, 0.4, 0.3, 0.25])",
            "confusion_matrix([0, 1, 2, 1, 0], [0, 1, 1, 1, 0])",
            "gx = grid([0, 1, 0, 1], 20)",
            "boundary_2d(reshape(iota(400), [400]) / 400, [20, 20], [[0,0],[1,1]], [0, 1])",
        ],
    },
    Demo {
        name: "Attention Pattern",
        intro: "The scaled-dot-product attention formula from 'Attention is All You Need', spelled out. Two Q and K matrices, scored and softmax'd, rendered as heatmaps. A second self-attention pass (Q attending to itself) shows the diagonal pattern that makes self-attention recognizable on sight.",
        takeaway: "You just built transformer attention in four lines: matmul + transpose + softmax. The heatmaps show where each query row puts probability mass -- self-attention concentrates on the diagonal; cross-attention doesn't.",
        lines: &[
            "Q = randn(17, [6, 4])",
            "K = randn(23, [6, 4])",
            "scores = matmul(Q, transpose(K)) / sqrt(4)",
            "A = softmax(scores, 1)",
            "svg(scores, \"heatmap\")",
            "svg(A, \"heatmap\")",
            "Qs = randn(17, [6, 4])",
            "Sself = matmul(Qs, transpose(Qs)) / sqrt(4)",
            "Aself = softmax(Sself, 1)",
            "svg(Aself, \"heatmap\")",
        ],
    },
    Demo {
        name: "Basics",
        intro: "The smallest possible MLPL tour: scalar arithmetic, elementwise array arithmetic with broadcasting, variable binding, and unary negation. If this makes sense, you can read the rest of the demos.",
        takeaway: "Operators apply elementwise; scalars broadcast; variables persist across REPL lines. That's the substrate every other demo builds on.",
        lines: &[
            "1 + 2",
            "3 * 4",
            "10 / 3",
            "[1, 2, 3] + [4, 5, 6]",
            "[1, 2, 3] * 10",
            "x = [10, 20, 30]",
            "y = x + 1",
            "y",
            "-[1, 2, 3]",
        ],
    },
    Demo {
        name: "Decision Boundary",
        intro: "Train a two-weight logistic regression on the AND function (only [1,1] is class 1), then visualize the learned probability surface over a 20x20 grid. The sigmoid's S-curve lives in 2D here, tilted by the weight vector.",
        takeaway: "300 gradient steps on four points produced a linear decision boundary that cleanly separates AND's one positive from its three negatives. The surface SVG shows where the model transitions from 'no' to 'yes' in input space.",
        lines: &[
            "X = [[0,0],[0,1],[1,0],[1,1]]",
            "y = [0, 0, 0, 1]",
            "w = zeros([2])",
            "b = 0",
            "lr = 1.0",
            "n = 4",
            "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
            "gx = grid([0, 1, 0, 1], 20)",
            "gz = matmul(gx, reshape(w, [2, 1])) + b",
            "gp = sigmoid(reshape(gz, [400]))",
            "surface = reshape(gp, [20, 20])",
            "tp = [[0,0,0],[0,1,0],[1,0,0],[1,1,1]]",
            "svg(surface, \"decision_boundary\", tp)",
        ],
    },
    Demo {
        name: "K-Means",
        intro: "K-means clustering without loops over points: all distances computed in one matmul, cluster assignments via argmax, and centroid updates via a one-hot-matrix-times-data trick. Three blobs in 2D, three centroids, ten iterations.",
        takeaway: "The final scatter shows points colored by their assigned cluster and the three centroids as a separate plot. Unsupervised -- no labels were passed in; the algorithm discovered the three groups from geometry alone.",
        lines: &[
            "D = blobs(7, 30, [[0, 0], [4, 4], [-4, 4]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "C = [[1, 1], [3, 3], [-3, 3]]",
            "repeat 10 { sqX = reshape(reduce_add(X*X, 1), [90, 1]); sqC = reshape(reduce_add(C*C, 1), [1, 3]); XC = matmul(X, transpose(C)); dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC; clus = argmax(-1 * dists, 1); jj = reshape(iota(3), [3, 1]); ll = reshape(clus, [1, 90]); diff = matmul(jj, ones([1, 90])) - matmul(ones([3, 1]), ll); A = eq(diff, 0); counts = reshape(reduce_add(A, 1), [3, 1]); sums = matmul(A, X); C = sums / matmul(counts, ones([1, 2])) }",
            "sqX = reshape(reduce_add(X*X, 1), [90, 1])",
            "sqC = reshape(reduce_add(C*C, 1), [1, 3])",
            "XC = matmul(X, transpose(C))",
            "dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC",
            "clus = argmax(-1 * dists, 1)",
            "scatter_labeled(X, clus)",
            "svg(C, \"scatter\")",
        ],
    },
    Demo {
        name: "Logistic Regression",
        intro: "The hello-world of supervised learning: 2D AND with hand-rolled gradient descent, final-accuracy check, a bar chart of per-point predictions, and a 1D loss sweep along the weight direction showing the minimum the optimizer found.",
        takeaway: "Accuracy prints as 1.0; the bar chart shows confident [0, 0, 0, 1] predictions; the loss curve has a clean bowl shape. This is the sanity-check pattern every classifier should pass.",
        lines: &[
            "X = [[0,0],[0,1],[1,0],[1,1]]",
            "y = [0, 0, 0, 1]",
            "w = zeros([2])",
            "b = 0",
            "lr = 1.0",
            "n = 4",
            "repeat 300 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
            "pred = sigmoid(matmul(X, reshape(w, [2, 1])) + b)",
            "rounded = gt(pred, 0.5)",
            "accuracy = mean(eq(reshape(rounded, [4]), y))",
            "accuracy",
            "svg(reshape(pred, [4]), \"bar\")",
            "ss = iota(16) / 10",
            "WS2 = matmul(reshape(ss, [16, 1]), reshape(w, [1, 2]))",
            "zs = matmul(WS2, transpose(X)) + matmul(reshape(ss * b, [16, 1]), ones([1, 4]))",
            "ps = sigmoid(zs)",
            "ys4 = matmul(ones([16, 1]), reshape(y, [1, 4]))",
            "losses = reduce_add((ps - ys4) * (ps - ys4), 1) / 4",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Loss Curve",
        intro: "Sweep a single weight across 25 values, compute the MSE loss against a linear target at each one, and plot the result. No training -- just the shape of the loss landscape.",
        takeaway: "A smooth parabolic curve with a clear minimum near the true weight. This is what gradient descent is walking down when you train; seeing the bowl makes the 'minimize the loss' story tangible.",
        lines: &[
            "x = [0, 1, 2, 3, 4]",
            "y = [0, 2, 4, 6, 8]",
            "ws = iota(25) / 4 - 1",
            "WS = reshape(ws, [25, 1])",
            "preds = matmul(WS, reshape(x, [1, 5]))",
            "YS = matmul(ones([25, 1]), reshape(y, [1, 5]))",
            "errs = preds - YS",
            "losses = reduce_add(errs * errs, 1) / 5",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Math Functions",
        intro: "The scalar and elementwise math primitives MLPL inherits from NumPy/APL conventions: exp, log, sqrt, abs, pow, sigmoid, tanh. Works on scalars and arrays uniformly.",
        takeaway: "Every primitive broadcasts over array inputs without a loop. If you know these names from NumPy you already know MLPL's math surface.",
        lines: &[
            "exp(0)",
            "exp([0, 1, 2])",
            "log(exp(1))",
            "sqrt([4, 9, 16, 25])",
            "abs([-3, 0, 5])",
            "pow([2, 3, 4], 2)",
            "sigmoid(0)",
            "sigmoid([-2, -1, 0, 1, 2])",
            "tanh_fn([-1, 0, 1])",
        ],
    },
    Demo {
        name: "Matrix Ops",
        intro: "Build a 3x4 matrix from iota, transpose it, read its shape and rank, and sum along both axes. The axis argument to reduce_add is how you go from a 2D tensor to a row-sum or column-sum vector.",
        takeaway: "reshape moves between flat and multi-dimensional views without copying; transpose swaps axes; reduce_add with an axis drops that axis. This is the APL half of MLPL -- shape is first-class and cheap to manipulate.",
        lines: &[
            "x = iota(12)",
            "m = reshape(x, [3, 4])",
            "m",
            "transpose(m)",
            "shape(m)",
            "rank(m)",
            "reduce_add(m, 0)",
            "reduce_add(m, 1)",
        ],
    },
    Demo {
        name: "Moons MLP",
        intro: "A two-layer tanh MLP trained with Adam on the 'two moons' synthetic dataset -- two interleaved half-circles that a single linear classifier can't separate. 200 training steps, then accuracy, a loss curve, a confusion matrix, and the learned decision boundary over a 30x30 grid.",
        takeaway: "A non-linear classifier with ~50 parameters separates the moons. The boundary SVG curves around each moon -- a visual proof that a hidden layer plus a non-linearity learned a non-linear decision surface.",
        lines: &[
            "M = moons(7, 120, 0.08)",
            "X = matmul(M, [[1,0],[0,1],[0,0]])",
            "y = reshape(matmul(M, [[0],[0],[1]]), [120])",
            "Y = one_hot(y, 2)",
            "O120 = ones([120, 1])",
            "W1 = param[2, 8]",
            "b1 = param[1, 8]",
            "W2 = param[8, 2]",
            "b2 = param[1, 2]",
            "W1 = randn(11, [2, 8]) * 0.5",
            "W2 = randn(12, [8, 2]) * 0.5",
            "train 200 { adam(mean((softmax(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), 1) - Y) * (softmax(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), 1) - Y)), [W1, b1, W2, b2], 0.05, 0.9, 0.999, 0.00000001); mean((softmax(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), 1) - Y) * (softmax(matmul(tanh_fn(matmul(X, W1) + matmul(O120, b1)), W2) + matmul(O120, b2), 1) - Y)) }",
            "Z1 = matmul(X, W1) + matmul(O120, b1)",
            "H = tanh_fn(Z1)",
            "Z2 = matmul(H, W2) + matmul(O120, b2)",
            "P = softmax(Z2, 1)",
            "pred = argmax(P, 1)",
            "accuracy = mean(eq(pred, y))",
            "accuracy",
            "loss_curve(last_losses)",
            "confusion_matrix(pred, y)",
            "G = grid([-1.5, 2.5, -1, 1.5], 30)",
            "O900 = ones([900, 1])",
            "GZ1 = matmul(G, W1) + matmul(O900, b1)",
            "GH = tanh_fn(GZ1)",
            "GZ2 = matmul(GH, W2) + matmul(O900, b2)",
            "GP = softmax(GZ2, 1)",
            "p1 = reshape(matmul(GP, [[0],[1]]), [900])",
            "boundary_2d(p1, [30, 30], X, y)",
        ],
    },
    Demo {
        name: "PCA",
        intro: "Principal Component Analysis without calling into a library: make anisotropic 2D data, center it, form the covariance matrix, run power iteration to find the top eigenvector, and project every point onto it. The top axis is the direction of maximum variance.",
        takeaway: "The scatter is colored by which side of zero each point's projection lands on; the line shows the found principal axis. Power iteration converges in ~10 steps to a direction that's clearly the long axis of the data cloud.",
        lines: &[
            "Xraw = randn(1, [60, 2])",
            "X = matmul(Xraw, [[1, 2], [0, 0.3]])",
            "cm = reduce_add(X, 0) / 60",
            "Xc = X - matmul(ones([60, 1]), reshape(cm, [1, 2]))",
            "Cov = matmul(transpose(Xc), Xc) / 60",
            "v = [1, 0]",
            "repeat 10 { v = matmul(Cov, v); v = v / sqrt(dot(v, v)) }",
            "coords = reshape(matmul(Xc, reshape(v, [2, 1])), [60])",
            "labels = gt(coords, 0)",
            "ends = matmul(reshape([-3, 3], [2, 1]), reshape(v, [1, 2]))",
            "line = ends + matmul(ones([2, 1]), reshape(cm, [1, 2]))",
            "scatter_labeled(X, labels)",
            "svg(line, \"line\")",
        ],
    },
    Demo {
        name: "Softmax Classifier",
        intro: "Three-class classification on 90 blob points. softmax + cross-entropy gradient descent (done in closed form here -- P - Y IS the gradient through the softmax+CE pair), then the usual accuracy / confusion-matrix / decision-boundary close.",
        takeaway: "A single linear layer with three output heads separates three well-spaced clusters. The decision boundary shows three roughly-wedge-shaped regions, one per class.",
        lines: &[
            "D = blobs(11, 30, [[0, 0], [4, 4], [-4, 4]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "tl = reshape(matmul(D, [[0],[0],[1]]), [90])",
            "Y = one_hot(tl, 3)",
            "W = zeros([2, 3])",
            "b = zeros([3])",
            "lr = 0.2",
            "repeat 300 { logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3])); P = softmax(logits, 1); dZ = P - Y; gW = matmul(transpose(X), dZ) / 90; gb = reduce_add(dZ, 0) / 90; W = W - lr * gW; b = b - lr * gb }",
            "logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3]))",
            "P = softmax(logits, 1)",
            "pred = argmax(P, 1)",
            "accuracy = mean(eq(pred, tl))",
            "accuracy",
            "confusion_matrix(pred, tl)",
            "G = grid([-6, 6, -3, 6], 30)",
            "gl = matmul(G, W) + matmul(ones([900, 1]), reshape(b, [1, 3]))",
            "gP = softmax(gl, 1)",
            "p0 = reshape(matmul(gP, [[1],[0],[0]]), [900])",
            "boundary_2d(p0, [30, 30], X, tl)",
        ],
    },
    // The interactive `Tiny LM` and `Tiny LM Generate` demos use a
    // smaller configuration than `demos/tiny_lm.mlpl` (V=280, d=32,
    // 200 steps) -- the CLI source is tuned for a serious run under
    // a native build where each training step is milliseconds. The
    // interpreter + WASM stack on the browser main thread is ~100x
    // slower per op; running the CLI configuration here hangs the
    // event loop past the browser's "unresponsive tab" timeout.
    // These entries mirror the "Training and Generating" tutorial
    // lesson's budget (V=260, d=16, block=8, 30 steps) which
    // completes in a few seconds interactively. For the serious
    // run, use the CLI: `mlpl-repl -f demos/tiny_lm.mlpl`.
    Demo {
        name: "Tiny LM Generate",
        intro: "End-to-end tiny transformer language model: tokenize a small corpus with BPE, wrap inputs as next-token pairs, build a 1-layer model (embed + causal_attention + rms_norm + linear head), train 30 Adam steps, then sample 20 tokens from a prompt and render the attention heatmap. The smallest program that trains and generates text.",
        takeaway: "A language model with a few thousand parameters produced a decoded string from a learned distribution and a [T,T] heatmap of what each position attended to. The loss curve should trend downward; the generated text is noisy because the model and budget are both tiny -- scale V, d, block, and step count for a serious run via the CLI.",
        lines: &[
            "corpus = load_preloaded(\"tiny_corpus\")",
            "tok    = train_bpe(corpus, 260, 0)",
            "ids    = apply_tokenizer(tok, corpus)",
            "X_all = shift_pairs_x(ids, 8)",
            "Y_all = shift_pairs_y(ids, 8)",
            "X     = reshape(X_all, [reduce_mul(shape(X_all))])",
            "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])",
            "V = 260 ; d = 16 ; h = 1",
            "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))",
            "experiment \"tiny_lm_gen\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }",
            "loss_curve(last_losses)",
            "prompt = apply_tokenizer(tok, \"the \")",
            "seq    = prompt",
            "repeat 20 { logits = apply(model, seq); last = last_row(logits); nxt = sample(top_k(last, 20), 0.8, step); seq = concat(seq, nxt) }",
            "decode(tok, seq)",
            "viz_ids = apply_tokenizer(tok, \"the quick\")",
            "attn_w  = attention_weights(model, viz_ids)",
            "svg(attn_w, \"heatmap\")",
        ],
    },
    Demo {
        name: "Tiny LM",
        intro: "Training-only variant of the Tiny LM: same model shape (embed + causal_attention + rms_norm + linear head, V=260, d=16, block=8), wrapped in experiment so the final metric is logged, then plot the loss curve across 30 Adam steps. No generation -- just a clean 'does the loss go down' demo.",
        takeaway: "Loss curve trends downward over 30 steps; the :experiments registry records the run's final loss metric. For generation + attention visualization, see 'Tiny LM Generate'. For a serious run with V=280 and 200 steps, use the CLI: mlpl-repl -f demos/tiny_lm.mlpl.",
        lines: &[
            "corpus = load_preloaded(\"tiny_corpus\")",
            "tok    = train_bpe(corpus, 260, 0)",
            "ids    = apply_tokenizer(tok, corpus)",
            "X_all = shift_pairs_x(ids, 8)",
            "Y_all = shift_pairs_y(ids, 8)",
            "X     = reshape(X_all, [reduce_mul(shape(X_all))])",
            "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])",
            "V = 260 ; d = 16 ; h = 1",
            "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))",
            "experiment \"tiny_lm\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }",
            "loss_curve(last_losses)",
        ],
    },
    Demo {
        name: "Tiny MLP",
        intro: "A hand-rolled 2-layer MLP on four blobs (two per class, XOR-ish layout). Forward + backward pass written out explicitly so every gradient is visible -- no autograd, no Model DSL. Ends with the decision-boundary render over a 30x30 grid.",
        takeaway: "You can see every matmul and every elementwise op in the training loop. For the same model with autograd hiding the backward pass, see 'Moons MLP'; for the same model as a Model DSL composition, see the tutorial's 'Model Composition' lesson.",
        lines: &[
            "D = blobs(3, 20, [[-2,-2],[2,2],[-2,2],[2,-2]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "raw = reshape(matmul(D, [[0],[0],[1]]), [80])",
            "y = gt(raw, 1.5)",
            "Y = one_hot(y, 2)",
            "W1 = randn(5, [2, 8]) * 0.5",
            "b1 = zeros([8])",
            "W2 = randn(6, [8, 2]) * 0.5",
            "b2 = zeros([2])",
            "lr = 0.2",
            "repeat 600 { Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8])); H = tanh_fn(Z1); Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2])); P = softmax(Z2, 1); dZ2 = P - Y; gW2 = matmul(transpose(H), dZ2) / 80; gb2 = reduce_add(dZ2, 0) / 80; dH = matmul(dZ2, transpose(W2)); dZ1 = dH * (1 - H * H); gW1 = matmul(transpose(X), dZ1) / 80; gb1 = reduce_add(dZ1, 0) / 80; W1 = W1 - lr * gW1; b1 = b1 - lr * gb1; W2 = W2 - lr * gW2; b2 = b2 - lr * gb2 }",
            "Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8]))",
            "H = tanh_fn(Z1)",
            "Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2]))",
            "P = softmax(Z2, 1)",
            "mlp_pred = argmax(P, 1)",
            "mean(eq(mlp_pred, y))",
            "confusion_matrix(mlp_pred, y)",
            "G = grid([-4, 4, -4, 4], 30)",
            "GZ1 = matmul(G, W1) + matmul(ones([900, 1]), reshape(b1, [1, 8]))",
            "GH = tanh_fn(GZ1)",
            "GZ2 = matmul(GH, W2) + matmul(ones([900, 1]), reshape(b2, [1, 2]))",
            "GP = softmax(GZ2, 1)",
            "p1 = reshape(matmul(GP, [[0],[1]]), [900])",
            "boundary_2d(p1, [30, 30], X, y)",
        ],
    },
    Demo {
        name: "Workspace Introspection",
        intro: "Tour of the REPL's introspection commands: :version, :wsid (workspace ID summary), :vars, :describe, :models, :experiments, :fns. Also shows how the axis-label annotation syntax (M : [batch, feat] = ...) shows up in :vars and :describe output.",
        takeaway: "You can always ask the REPL what's in your session. :describe on a variable prints shape + labels + a preview; on a model, the layer tree; on a builtin, the signature and one-line doc. :experiments shows every tracked run.",
        lines: &[
            ":version",
            ":wsid",
            "x = 42",
            "v = iota(5)",
            "M : [batch, feat] = reshape(iota(6), [2, 3])",
            ":vars",
            ":describe v",
            "mdl = chain(linear(2, 4, 11), relu_layer(), linear(4, 2, 12))",
            ":models",
            ":describe mdl",
            "tok = train_bpe(\"abababab\", 260, 0)",
            ":describe tok",
            "W = param[3, 2]",
            ":vars",
            ":wsid",
            "experiment \"workspace_demo\" { loss_metric = 0.25; accuracy_metric = 0.94 }",
            ":experiments",
            ":describe matmul",
            ":fns",
        ],
    },
    Demo {
        name: "Visualizations",
        intro: "The four primitive svg() types -- scatter, line, bar, heatmap -- each in one line. Rendered inline; a download button next to each SVG saves it as a file.",
        takeaway: "Every plot is one call with a data array and a type string. There is no plotting API to learn beyond 'pass the right shape.'",
        lines: &[
            "svg([[0,0],[1,1],[2,4],[3,9],[4,16]], \"scatter\")",
            "svg([1, 3, 2, 5, 4, 6], \"line\")",
            "svg([3, 1, 4, 1, 5, 9, 2, 6], \"bar\")",
            "svg(reshape(iota(25), [5, 5]), \"heatmap\")",
        ],
    },
];
