pub struct Demo {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

// Demos are listed alphabetically by `name`.
pub const DEMOS: &[Demo] = &[
    Demo {
        name: "Analysis Helpers",
        lines: &[
            "hist([1, 2, 2, 3, 3, 3, 4, 4, 5], 5)",
            "scatter_labeled([[0,0],[1,1],[0,1],[1,0]], [0, 0, 1, 1])",
            "loss_curve([5, 3, 2, 1.5, 1.0, 0.7, 0.5, 0.4, 0.3, 0.25])",
            "confusion_matrix([0, 1, 2, 1, 0], [0, 1, 1, 1, 0])",
            "gx = grid([0, 1, 0, 1], 20)",
            "boundary_2d(reshape(iota(400), [400]) / 400, [20, 20], [[0,0],[1,1]], [0, 1])",
        ],
    },
    Demo {
        name: "Basics",
        lines: &[
            "1 + 2",
            "3 * 4",
            "10 / 3",
            "[1, 2, 3] + [4, 5, 6]",
            "[1, 2, 3] * 10",
            "x = [10, 20, 30]",
            "y = x + 1",
            "y",
            "-[1, 2, 3]",
        ],
    },
    Demo {
        name: "Decision Boundary",
        lines: &[
            "X = [[0,0],[0,1],[1,0],[1,1]]",
            "y = [0, 0, 0, 1]",
            "w = zeros([2])",
            "b = 0",
            "lr = 1.0",
            "n = 4",
            "repeat 400 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
            "gx = grid([0, 1, 0, 1], 20)",
            "gz = matmul(gx, reshape(w, [2, 1])) + b",
            "gp = sigmoid(reshape(gz, [400]))",
            "surface = reshape(gp, [20, 20])",
            "train = [[0,0,0],[0,1,0],[1,0,0],[1,1,1]]",
            "svg(surface, \"decision_boundary\", train)",
        ],
    },
    Demo {
        name: "K-Means",
        lines: &[
            "D = blobs(7, 30, [[0, 0], [4, 4], [-4, 4]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "C = [[1, 1], [3, 3], [-3, 3]]",
            "repeat 10 { sqX = reshape(reduce_add(X*X, 1), [90, 1]); sqC = reshape(reduce_add(C*C, 1), [1, 3]); XC = matmul(X, transpose(C)); dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC; clus = argmax(-1 * dists, 1); jj = reshape(iota(3), [3, 1]); ll = reshape(clus, [1, 90]); diff = matmul(jj, ones([1, 90])) - matmul(ones([3, 1]), ll); A = eq(diff, 0); counts = reshape(reduce_add(A, 1), [3, 1]); sums = matmul(A, X); C = sums / matmul(counts, ones([1, 2])) }",
            "sqX = reshape(reduce_add(X*X, 1), [90, 1])",
            "sqC = reshape(reduce_add(C*C, 1), [1, 3])",
            "XC = matmul(X, transpose(C))",
            "dists = matmul(sqX, ones([1, 3])) + matmul(ones([90, 1]), sqC) - 2*XC",
            "clus = argmax(-1 * dists, 1)",
            "scatter_labeled(X, clus)",
            "svg(C, \"scatter\")",
        ],
    },
    Demo {
        name: "Logistic Regression",
        lines: &[
            "X = [[0,0],[0,1],[1,0],[1,1]]",
            "y = [0, 0, 0, 1]",
            "w = zeros([2])",
            "b = 0",
            "lr = 1.0",
            "n = 4",
            "repeat 300 { z = matmul(X, reshape(w, [2, 1])) + b; pred = sigmoid(z); dz = pred - reshape(y, [4, 1]); dw = reshape(matmul(transpose(X), dz), [2]) / n; db = mean(dz); w = w - lr * dw; b = b - lr * db }",
            "pred = sigmoid(matmul(X, reshape(w, [2, 1])) + b)",
            "rounded = gt(pred, 0.5)",
            "accuracy = mean(eq(reshape(rounded, [4]), y))",
            "accuracy",
            "svg(reshape(pred, [4]), \"bar\")",
            "ss = iota(16) / 10",
            "WS2 = matmul(reshape(ss, [16, 1]), reshape(w, [1, 2]))",
            "zs = matmul(WS2, transpose(X)) + matmul(reshape(ss * b, [16, 1]), ones([1, 4]))",
            "ps = sigmoid(zs)",
            "ys4 = matmul(ones([16, 1]), reshape(y, [1, 4]))",
            "losses = reduce_add((ps - ys4) * (ps - ys4), 1) / 4",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Loss Curve",
        lines: &[
            "x = [0, 1, 2, 3, 4]",
            "y = [0, 2, 4, 6, 8]",
            "ws = iota(25) / 4 - 1",
            "WS = reshape(ws, [25, 1])",
            "preds = matmul(WS, reshape(x, [1, 5]))",
            "YS = matmul(ones([25, 1]), reshape(y, [1, 5]))",
            "errs = preds - YS",
            "losses = reduce_add(errs * errs, 1) / 5",
            "svg(losses, \"line\")",
        ],
    },
    Demo {
        name: "Math Functions",
        lines: &[
            "exp(0)",
            "exp([0, 1, 2])",
            "log(exp(1))",
            "sqrt([4, 9, 16, 25])",
            "abs([-3, 0, 5])",
            "pow([2, 3, 4], 2)",
            "sigmoid(0)",
            "sigmoid([-2, -1, 0, 1, 2])",
            "tanh_fn([-1, 0, 1])",
        ],
    },
    Demo {
        name: "Matrix Ops",
        lines: &[
            "x = iota(12)",
            "m = reshape(x, [3, 4])",
            "m",
            "transpose(m)",
            "shape(m)",
            "rank(m)",
            "reduce_add(m, 0)",
            "reduce_add(m, 1)",
        ],
    },
    Demo {
        name: "PCA",
        lines: &[
            "Xraw = randn(1, [60, 2])",
            "X = matmul(Xraw, [[1, 2], [0, 0.3]])",
            "cm = reduce_add(X, 0) / 60",
            "Xc = X - matmul(ones([60, 1]), reshape(cm, [1, 2]))",
            "Cov = matmul(transpose(Xc), Xc) / 60",
            "v = [1, 0]",
            "repeat 10 { v = matmul(Cov, v); v = v / sqrt(dot(v, v)) }",
            "coords = reshape(matmul(Xc, reshape(v, [2, 1])), [60])",
            "labels = gt(coords, 0)",
            "ends = matmul(reshape([-3, 3], [2, 1]), reshape(v, [1, 2]))",
            "line = ends + matmul(ones([2, 1]), reshape(cm, [1, 2]))",
            "scatter_labeled(X, labels)",
            "svg(line, \"line\")",
        ],
    },
    Demo {
        name: "Softmax Classifier",
        lines: &[
            "D = blobs(11, 30, [[0, 0], [4, 4], [-4, 4]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "tl = reshape(matmul(D, [[0],[0],[1]]), [90])",
            "Y = one_hot(tl, 3)",
            "W = zeros([2, 3])",
            "b = zeros([3])",
            "lr = 0.2",
            "repeat 300 { logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3])); P = softmax(logits, 1); dZ = P - Y; gW = matmul(transpose(X), dZ) / 90; gb = reduce_add(dZ, 0) / 90; W = W - lr * gW; b = b - lr * gb }",
            "logits = matmul(X, W) + matmul(ones([90, 1]), reshape(b, [1, 3]))",
            "P = softmax(logits, 1)",
            "pred = argmax(P, 1)",
            "accuracy = mean(eq(pred, tl))",
            "accuracy",
            "confusion_matrix(pred, tl)",
            "G = grid([-6, 6, -3, 6], 30)",
            "gl = matmul(G, W) + matmul(ones([900, 1]), reshape(b, [1, 3]))",
            "gP = softmax(gl, 1)",
            "p0 = reshape(matmul(gP, [[1],[0],[0]]), [900])",
            "boundary_2d(p0, [30, 30], X, tl)",
        ],
    },
    Demo {
        name: "Tiny MLP",
        lines: &[
            "D = blobs(3, 20, [[-2,-2],[2,2],[-2,2],[2,-2]])",
            "X = matmul(D, [[1,0],[0,1],[0,0]])",
            "raw = reshape(matmul(D, [[0],[0],[1]]), [80])",
            "y = gt(raw, 1.5)",
            "Y = one_hot(y, 2)",
            "W1 = randn(5, [2, 8]) * 0.5",
            "b1 = zeros([8])",
            "W2 = randn(6, [8, 2]) * 0.5",
            "b2 = zeros([2])",
            "lr = 0.2",
            "repeat 600 { Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8])); H = tanh_fn(Z1); Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2])); P = softmax(Z2, 1); dZ2 = P - Y; gW2 = matmul(transpose(H), dZ2) / 80; gb2 = reduce_add(dZ2, 0) / 80; dH = matmul(dZ2, transpose(W2)); dZ1 = dH * (1 - H * H); gW1 = matmul(transpose(X), dZ1) / 80; gb1 = reduce_add(dZ1, 0) / 80; W1 = W1 - lr * gW1; b1 = b1 - lr * gb1; W2 = W2 - lr * gW2; b2 = b2 - lr * gb2 }",
            "Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8]))",
            "H = tanh_fn(Z1)",
            "Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2]))",
            "P = softmax(Z2, 1)",
            "mlp_pred = argmax(P, 1)",
            "mean(eq(mlp_pred, y))",
            "confusion_matrix(mlp_pred, y)",
            "G = grid([-4, 4, -4, 4], 30)",
            "GZ1 = matmul(G, W1) + matmul(ones([900, 1]), reshape(b1, [1, 8]))",
            "GH = tanh_fn(GZ1)",
            "GZ2 = matmul(GH, W2) + matmul(ones([900, 1]), reshape(b2, [1, 2]))",
            "GP = softmax(GZ2, 1)",
            "p1 = reshape(matmul(GP, [[0],[1]]), [900])",
            "boundary_2d(p1, [30, 30], X, y)",
        ],
    },
    Demo {
        name: "Visualizations",
        lines: &[
            "svg([[0,0],[1,1],[2,4],[3,9],[4,16]], \"scatter\")",
            "svg([1, 3, 2, 5, 4, 6], \"line\")",
            "svg([3, 1, 4, 1, 5, 9, 2, 6], \"bar\")",
            "svg(reshape(iota(25), [5, 5]), \"heatmap\")",
        ],
    },
];
