//! Saga 33 step 001: ViT / pets / vision demos extracted
//! from `demos.rs`. Pure compile-time data.

use crate::demos::Demo;

pub const VIT_ATTENTION_PATTERN: Demo = Demo {
    category: "Vision (ViT)",
    name: "ViT Attention Pattern (no training)",
    intro: "Vision [[Transformer]] pipeline end-to-end on a synthetic 64x64 RGB image, no training. patchify(x, 16) cuts the image into a 4x4 grid of 16 patches; each patch flattens P*P*C = 768 floats. A linear projection embeds them to d_model=128, a randn CLS token is prepended via concat(cls, patches, 0), a randn positional embedding is added, and one attention head computes its softmax weight matrix [17, 17] (16 patch tokens + 1 CLS). The heatmap is what an UNTRAINED ViT head pays attention to -- essentially nothing useful. The 'Pets: cat vs dog (quick)' demo trains the same architecture on pets_tiny.",
    takeaway: "The ViT recipe is shorter than it looks: patchify + linear-embed + CLS-prepend + pos-add + attention. Five new builtins (patchify, concat axis 0, randn, matmul, softmax) compose into the same forward-pass topology the original ViT paper drew. Without training, the attention weights are random; the row-sum sanity check at the end confirms softmax did its job regardless.",
    lines: &[
        "img = randn(101, [1, 3, 64, 64])                       # one synthetic 64x64 RGB image",
        "tokens_4d = patchify(img, 16)                          # [1, 16, 768] -- 4x4 grid of P*P*C patches",
        "tokens    = reshape(tokens_4d, [16, 768])              # drop the singleton batch dim",
        "Wp        = randn(201, [768, 128]) / sqrt(768)         # linear patch embedding to d_model = 128",
        "patches   = matmul(tokens, Wp)                         # [16, 128]",
        "cls = randn(301, [1, 128])                             # learnable CLS token (randn for the no-training demo)",
        "seq_no_pos = concat(cls, patches, 0)                   # prepend CLS along the sequence axis -> [17, 128]",
        "pos = randn(401, [17, 128])                            # positional embedding",
        "seq = seq_no_pos + pos                                 # add positions",
        "Wq = randn(501, [128, 128]) / sqrt(128)                # one attention head, d_k = 128",
        "Wk = randn(502, [128, 128]) / sqrt(128)",
        "q  = matmul(seq, Wq)",
        "k  = matmul(seq, Wk)",
        "scores = matmul(q, transpose(k)) / sqrt(128)           # scaled dot-product",
        "A = softmax(scores, 1)                                 # row-stochastic attention pattern [17, 17]",
        "svg(A, \"heatmap\")                                    # render the heatmap",
        "row_sums = reduce_add(A, 1)                            # sanity: every row sums to 1.0",
        "row_sums",
    ],
};

pub const PETS_CAT_VS_DOG_QUICK: Demo = Demo {
    category: "Vision (ViT)",
    name: "Pets: cat vs dog (quick)",
    intro: "Trained [[ViT (Vision Transformer)]] end-to-end on a balanced 8-image subset of [[Oxford-IIIT Pet dataset]] (4 cats + 4 dogs). 30 full-batch [[Adam]] steps with single-head [[Attention]] (`attention(128, 1)`) and a tiny [[MLP (Multi-Layer Perceptron)]] classifier head. The longer 20-image / 100-step version lives in `demos/vit_single_head_quick.mlpl`; this in-browser variant is scaled down so the train loop completes in seconds. The 30 adam steps run as 6 chunks of `train 5 { ... }` so the browser tab stays responsive between chunks (a single `train 30` would block the WASM thread for the whole run).",
    takeaway: "ViT in MLPL is the same five-step recipe as the no-training demo plus a [[Train (loop)]] and an [[Adam]] call. The forward expression has to be inlined into [[Adam]] because [[Backpropagation]] walks the expression tree (let-bindings would create non-differentiable leaves). First-token pooling stands in for a learned CLS token. Each `train 5` chunk overwrites `last_losses`, so the demo accumulates `all_losses = concat(all_losses, last_losses, 0)` between chunks; Adam momentum persists across chunks via the session env, so this is mathematically identical to a single `train 30`. The loss curve at the end shows binary [[Cross entropy]] falling from ~0.69 (random) toward 0 (overfit); the final accuracy on the 8 training images is the scalar at the very bottom.",
    lines: &[
        "# Balanced 8-image subset (4 cats + 4 dogs) extracted",
        "# from pets_tiny via take + concat.",
        "pets = load_preloaded(\"pets_tiny\")",
        "c0 = reshape(take(pets.X, 0, 0), [1, 3, 64, 64])",
        "c1 = reshape(take(pets.X, 0, 1), [1, 3, 64, 64])",
        "c2 = reshape(take(pets.X, 0, 2), [1, 3, 64, 64])",
        "c3 = reshape(take(pets.X, 0, 3), [1, 3, 64, 64])",
        "d0 = reshape(take(pets.X, 0, 100), [1, 3, 64, 64])",
        "d1 = reshape(take(pets.X, 0, 101), [1, 3, 64, 64])",
        "d2 = reshape(take(pets.X, 0, 102), [1, 3, 64, 64])",
        "d3 = reshape(take(pets.X, 0, 103), [1, 3, 64, 64])",
        "cats = concat(concat(concat(c0, c1, 0), c2, 0), c3, 0)",
        "dogs = concat(concat(concat(d0, d1, 0), d2, 0), d3, 0)",
        "X    = concat(cats, dogs, 0)                                # [8, 3, 64, 64]",
        "ly0 = reshape(take(pets.Y, 0, 0),   [1])",
        "ly1 = reshape(take(pets.Y, 0, 1),   [1])",
        "ly2 = reshape(take(pets.Y, 0, 2),   [1])",
        "ly3 = reshape(take(pets.Y, 0, 3),   [1])",
        "ld0 = reshape(take(pets.Y, 0, 100), [1])",
        "ld1 = reshape(take(pets.Y, 0, 101), [1])",
        "ld2 = reshape(take(pets.Y, 0, 102), [1])",
        "ld3 = reshape(take(pets.Y, 0, 103), [1])",
        "ycats = concat(concat(concat(ly0, ly1, 0), ly2, 0), ly3, 0)",
        "ydogs = concat(concat(concat(ld0, ld1, 0), ld2, 0), ld3, 0)",
        "Y     = concat(ycats, ydogs, 0)                             # [8] -- 0=cat, 1=dog",
        "# Model layers.",
        "linear_p   = linear(768, 128, 17)                            # patch embedding",
        "attn       = attention(128, 1, 23)                           # single-head, d_model=128",
        "classifier = chain(linear(128, 64, 31), relu_layer(), linear(64, 2, 37))",
        "# 30 full-batch adam steps run as 6 train blocks of 5",
        "# steps each, so the browser tab stays responsive (the",
        "# REPL yields between lines but cannot interrupt a",
        "# single long train). Adam momentum persists across the",
        "# chunks via the session env -- mathematically identical",
        "# to one train 30. Forward pipeline:",
        "#   patchify(X, 16) -> reshape -> linear -> reshape",
        "#   -> attention(rank-3) -> take(_, 1, 0) (first-token)",
        "#   -> classifier -> cross_entropy(_, Y)",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = last_losses",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "# Loss curve: full 30-step trajectory.",
        "loss_curve(all_losses)",
        "# Final training accuracy on the 8-image set.",
        "logits   = apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0))",
        "preds    = argmax(logits, 1)",
        "correct  = eq(preds, Y)",
        "accuracy = reduce_add(correct) / 8",
        "accuracy",
        "# Inspecting the tensor: pets.X is [200, 3, 64, 64] --",
        "# too big to print in full. The REPL summarizes it as",
        "# <DenseArray shape=...> with a 3-value preview. To",
        "# peek at actual values, chain `take` down to <= 64",
        "# elements:",
        "take(pets.X, 0, 0)                          # one image -> [3, 64, 64] (still summarized)",
        "take(take(pets.X, 0, 0), 0, 0)              # one channel -> [64, 64] (still summarized)",
        "take(take(take(pets.X, 0, 0), 0, 0), 0, 30) # one row of one channel -> [64] (prints in full)",
        "take(take(take(take(pets.X, 0, 0), 0, 0), 0, 30), 0, 30) # single pixel value -> scalar",
        "# preds and Y on the trained 8-image batch:",
        "preds",
        "Y",
    ],
};

pub const PETS_PREDICT_GALLERY: Demo = Demo {
    category: "Vision (ViT)",
    name: "Pets: predict + gallery",
    intro: "Train a Vision [[Transformer]] on 16 balanced cat/dog images, then render the labeled gallery: each thumbnail gets an `actual / predicted` caption underneath. Heavy: about 1-3 minutes in the browser. Misclassifications stand out because the two captions disagree (0/1 or 1/0).",
    takeaway: "The new pieces vs the quick demo: `predict_batch(model, X)` runs forward and returns argmax integer labels in one call; `svg(images, \"gallery\", overlay)` accepts an optional `[N]` or `[N, K]` overlay tensor and renders the values as text under each thumbnail. With actual + predicted side-by-side, you can finally point at a specific cat/dog photo and see what the model said. The 50-step train loop overfits, so almost every prediction matches the actual; the demonstration is the visualization, not the model quality.",
    lines: &[
        "pets = load_preloaded(\"pets_tiny\")",
        "c0 = reshape(take(pets.X, 0, 0), [1, 3, 64, 64])",
        "c1 = reshape(take(pets.X, 0, 1), [1, 3, 64, 64])",
        "c2 = reshape(take(pets.X, 0, 2), [1, 3, 64, 64])",
        "c3 = reshape(take(pets.X, 0, 3), [1, 3, 64, 64])",
        "c4 = reshape(take(pets.X, 0, 4), [1, 3, 64, 64])",
        "c5 = reshape(take(pets.X, 0, 5), [1, 3, 64, 64])",
        "c6 = reshape(take(pets.X, 0, 6), [1, 3, 64, 64])",
        "c7 = reshape(take(pets.X, 0, 7), [1, 3, 64, 64])",
        "d0 = reshape(take(pets.X, 0, 100), [1, 3, 64, 64])",
        "d1 = reshape(take(pets.X, 0, 101), [1, 3, 64, 64])",
        "d2 = reshape(take(pets.X, 0, 102), [1, 3, 64, 64])",
        "d3 = reshape(take(pets.X, 0, 103), [1, 3, 64, 64])",
        "d4 = reshape(take(pets.X, 0, 104), [1, 3, 64, 64])",
        "d5 = reshape(take(pets.X, 0, 105), [1, 3, 64, 64])",
        "d6 = reshape(take(pets.X, 0, 106), [1, 3, 64, 64])",
        "d7 = reshape(take(pets.X, 0, 107), [1, 3, 64, 64])",
        "cats_2 = concat(c0, c1, 0)",
        "cats_4 = concat(concat(cats_2, c2, 0), c3, 0)",
        "cats_6 = concat(concat(cats_4, c4, 0), c5, 0)",
        "cats   = concat(concat(cats_6, c6, 0), c7, 0)",
        "dogs_2 = concat(d0, d1, 0)",
        "dogs_4 = concat(concat(dogs_2, d2, 0), d3, 0)",
        "dogs_6 = concat(concat(dogs_4, d4, 0), d5, 0)",
        "dogs   = concat(concat(dogs_6, d6, 0), d7, 0)",
        "X = concat(cats, dogs, 0)",
        "ly0 = reshape(take(pets.Y, 0, 0),   [1])",
        "ly1 = reshape(take(pets.Y, 0, 1),   [1])",
        "ly2 = reshape(take(pets.Y, 0, 2),   [1])",
        "ly3 = reshape(take(pets.Y, 0, 3),   [1])",
        "ly4 = reshape(take(pets.Y, 0, 4),   [1])",
        "ly5 = reshape(take(pets.Y, 0, 5),   [1])",
        "ly6 = reshape(take(pets.Y, 0, 6),   [1])",
        "ly7 = reshape(take(pets.Y, 0, 7),   [1])",
        "ld0 = reshape(take(pets.Y, 0, 100), [1])",
        "ld1 = reshape(take(pets.Y, 0, 101), [1])",
        "ld2 = reshape(take(pets.Y, 0, 102), [1])",
        "ld3 = reshape(take(pets.Y, 0, 103), [1])",
        "ld4 = reshape(take(pets.Y, 0, 104), [1])",
        "ld5 = reshape(take(pets.Y, 0, 105), [1])",
        "ld6 = reshape(take(pets.Y, 0, 106), [1])",
        "ld7 = reshape(take(pets.Y, 0, 107), [1])",
        "yca_2 = concat(ly0, ly1, 0)",
        "yca_4 = concat(concat(yca_2, ly2, 0), ly3, 0)",
        "yca_6 = concat(concat(yca_4, ly4, 0), ly5, 0)",
        "yca   = concat(concat(yca_6, ly6, 0), ly7, 0)",
        "ydo_2 = concat(ld0, ld1, 0)",
        "ydo_4 = concat(concat(ydo_2, ld2, 0), ld3, 0)",
        "ydo_6 = concat(concat(ydo_4, ld4, 0), ld5, 0)",
        "ydo   = concat(concat(ydo_6, ld6, 0), ld7, 0)",
        "Y = concat(yca, ydo, 0)",
        "# Model: shared with the quick demo.",
        "linear_p   = linear(768, 128, 17)",
        "attn       = attention(128, 1, 23)",
        "classifier = chain(linear(128, 64, 31), relu_layer(), linear(64, 2, 37))",
        "# Training loop split into 6 chunks of 5 steps. Each",
        "# chunk runs synchronously in WASM (~5s); the demo runner",
        "# yields to the browser between chunks so the tab stays",
        "# responsive and you can see incremental progress. Adam's",
        "# momentum state persists across chunks via env, so this",
        "# is mathematically equivalent to a single train 30.",
        "# ============================================================",
        "# Part 1 of 6: first 5 adam steps. Initializes all_losses.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = last_losses",
        "# ============================================================",
        "# Part 2 of 6: another 5 steps, appends to all_losses.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "# ============================================================",
        "# Part 3 of 6.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "# ============================================================",
        "# Part 4 of 6.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "# ============================================================",
        "# Part 5 of 6.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "# ============================================================",
        "# Part 6 of 6: final chunk. Training is done after this line.",
        "# ============================================================",
        "train 5 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0)), Y) }",
        "all_losses = concat(all_losses, last_losses, 0)",
        "loss_curve(all_losses)",
        "# Predict labels then render the labeled gallery.",
        "preds = predict_batch(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [256, 768])), [16, 16, 128])), 1, 0))",
        "preds_2col = concat(reshape(Y, [16, 1]), reshape(preds, [16, 1]), 1)",
        "accuracy = reduce_add(eq(preds, Y)) / 16",
        "accuracy",
        "svg(X, \"gallery\", preds_2col)",
    ],
};

pub const VIT_MULTI_HEAD_ATTENTION_PATTERN: Demo = Demo {
    category: "Vision (ViT)",
    name: "ViT Multi-Head Attention Pattern (no training)",
    intro: "The multi-head sibling of the single-head ViT attention pattern demo. Same synthetic 64x64 image, same patchify+linear-embed+CLS+pos pipeline, but `attention(128, 4, ...)` instead of one head. attention_weights returns [4, 17, 17]; the `heatmap_grid` viz type renders all four heads in a 2x2 grid so per-head differences are visible at a glance. UNTRAINED: all four heads draw from the same randn distribution and look uniform-random with no structure. Compare with the trained companion demo to see what gradient descent buys.",
    takeaway: "[[Multi-head attention]] is just single-head attention applied to h independent subspaces of d_model. Before training, the four heads start from independent randn projections and produce four uniformly-random attention patterns. The architecture doesn't tell heads to specialize; the visualization here is the negative control -- the baseline that the trained demo is judged against.",
    lines: &[
        "img = randn(101, [1, 3, 64, 64])                       # one synthetic 64x64 RGB image",
        "tokens_4d = patchify(img, 16)                          # [1, 16, 768]",
        "tokens    = reshape(tokens_4d, [16, 768])",
        "Wp        = randn(201, [768, 128]) / sqrt(768)         # linear patch embedding to d_model = 128",
        "patches   = matmul(tokens, Wp)",
        "cls = randn(301, [1, 128])                             # CLS token",
        "seq_no_pos = concat(cls, patches, 0)                   # [17, 128]",
        "pos = randn(401, [17, 128])",
        "seq = seq_no_pos + pos                                 # [17, 128]",
        "# Four-head attention via the Model DSL. d_k = 128/4 = 32.",
        "mdl = attention(128, 4, 17)",
        "# attention_weights returns [heads, T, T] for multi-head, rank-2 input.",
        "A = attention_weights(mdl, seq)                        # [4, 17, 17]",
        "# heatmap_grid renders [N, R, C] as a 2x2 grid of",
        "# heatmaps with per-cell colormaps.",
        "svg(A, \"heatmap_grid\")",
        "# Sanity: per-(head, row) softmax sums = 1.",
        "row_sums = reduce_add(A, 2)                            # [4, 17]",
        "row_sums",
    ],
};

pub const PETS_MULTI_HEAD_VIT: Demo = Demo {
    category: "Vision (ViT)",
    name: "Pets: multi-head ViT (quick + viz)",
    intro: "Trained 4-head [[ViT (Vision Transformer)]] on a balanced 8-image cat/dog subset, reaching 100% training accuracy in 30 [[Adam]] steps with per-head attention maps rendered after training. Same architecture as the single-head quick demo but [[Multi-head attention]] (`attention(128, 4)`) and an [[attention_weights (builtin)]] + [[heatmap_grid (viz type)]] viz at the end. Compare the heatmap_grid output here with the UNTRAINED 'ViT Multi-Head Attention Pattern' demo -- the four heads start identical and end specialized. (Click any underlined term to open its glossary entry.)",
    takeaway: "Training accuracy = 1.0 -- the four heads + classifier learn the 8-image set in 30 adam steps. The four [16, 16] cells show what each attention head learned: row i = patch i (in row-major order from top-left to bottom-right of a 4x4 grid over the 64x64 image); column j = how strongly patch i attends to patch j. A bright cell at row i column j means head h thinks patch i should pull information from patch j. After training the heads are NOT identical -- the same architecture, the same input, the same optimizer, but four different attention patterns because each head's Q/K/V projection was randomly initialized to a different starting subspace, and gradient descent then pushed each one toward whatever role minimized cross-entropy for THAT subspace. Compare with the untrained 'ViT Multi-Head Attention Pattern' demo (run it first) where all four heads look the same uniform-random noise -- the specialization here is entirely learned, not architectural. Common post-training patterns: one head concentrates attention into a single column (a 'this patch is salient' detector); one stays diffuse (an 'aggregate everything' channel); the remaining two pick intermediate roles. The architecture says 'split d_model into 4 subspaces and run attention in each'; gradient descent says what each subspace pays attention to.",
    lines: &[
        "pets = load_preloaded(\"pets_tiny\")",
        "c0 = reshape(take(pets.X, 0, 0), [1, 3, 64, 64])",
        "c1 = reshape(take(pets.X, 0, 1), [1, 3, 64, 64])",
        "c2 = reshape(take(pets.X, 0, 2), [1, 3, 64, 64])",
        "c3 = reshape(take(pets.X, 0, 3), [1, 3, 64, 64])",
        "d0 = reshape(take(pets.X, 0, 100), [1, 3, 64, 64])",
        "d1 = reshape(take(pets.X, 0, 101), [1, 3, 64, 64])",
        "d2 = reshape(take(pets.X, 0, 102), [1, 3, 64, 64])",
        "d3 = reshape(take(pets.X, 0, 103), [1, 3, 64, 64])",
        "cats = concat(concat(concat(c0, c1, 0), c2, 0), c3, 0)",
        "dogs = concat(concat(concat(d0, d1, 0), d2, 0), d3, 0)",
        "X    = concat(cats, dogs, 0)",
        "ly0 = reshape(take(pets.Y, 0, 0),   [1])",
        "ly1 = reshape(take(pets.Y, 0, 1),   [1])",
        "ly2 = reshape(take(pets.Y, 0, 2),   [1])",
        "ly3 = reshape(take(pets.Y, 0, 3),   [1])",
        "ld0 = reshape(take(pets.Y, 0, 100), [1])",
        "ld1 = reshape(take(pets.Y, 0, 101), [1])",
        "ld2 = reshape(take(pets.Y, 0, 102), [1])",
        "ld3 = reshape(take(pets.Y, 0, 103), [1])",
        "ycats = concat(concat(concat(ly0, ly1, 0), ly2, 0), ly3, 0)",
        "ydogs = concat(concat(concat(ld0, ld1, 0), ld2, 0), ld3, 0)",
        "Y     = concat(ycats, ydogs, 0)",
        "# Model: four-head attention.",
        "linear_p   = linear(768, 128, 17)",
        "attn       = attention(128, 4, 23)                           # <-- 4 heads (was 1)",
        "classifier = chain(linear(128, 64, 31), relu_layer(), linear(64, 2, 37))",
        "# 30 full-batch adam steps. Same forward pipeline as the",
        "# single-head quick demo, just with heads=4.",
        "train 30 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "loss_curve(last_losses)",
        "# Training accuracy on the 8-image set.",
        "logits   = apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0))",
        "preds    = argmax(logits, 1)",
        "correct  = eq(preds, Y)",
        "accuracy = reduce_add(correct) / 8",
        "# Attention maps on the first (cat) image: pull image 0,",
        "# embed it, take batch slice 0, run attention_weights ->",
        "# [4, 16, 16] (heads x T_no_cls x T_no_cls).",
        "test_img    = reshape(take(pets.X, 0, 0), [1, 3, 64, 64])",
        "test_tokens = reshape(apply(linear_p, reshape(patchify(test_img, 16), [16, 768])), [16, 128])",
        "attn_maps   = attention_weights(attn, test_tokens)",
        "svg(attn_maps, \"heatmap_grid\")",
        "# Labeled image gallery: actual / predicted under each",
        "# thumbnail, same overlay format as the predict+gallery",
        "# demo. With heads=4 you can see WHICH images the model",
        "# got right alongside the per-head attention maps above.",
        "preds_2col = concat(reshape(Y, [8, 1]), reshape(preds, [8, 1]), 1)",
        "svg(X, \"gallery\", preds_2col)",
        "accuracy",
    ],
};

pub const PETS_ATTENTION_OVERLAY: Demo = Demo {
    category: "Vision (ViT)",
    name: "Pets: attention overlay (per-head)",
    intro: "Same trained 4-head [[ViT (Vision Transformer)]] as the multi-head demo above (training accuracy 1.0 on the 8-image set after 30 adam steps), but the per-head attention is rendered OVER the test image instead of as an abstract [16, 16] matrix. Each cell of the output is the same cat photo with one head's attention pattern painted on top: bright yellow patches are what THAT head attends to, dark purple patches are ignored. The four cells look DIFFERENT after training -- the heads start identical at initialization and end specialized via gradient descent. Uses the new [[attention_overlay (viz type)]] viz. (Click any underlined term to open its glossary entry.)",
    takeaway: "What you are looking at: the SAME 64x64 cat image rendered four times, with one of the trained model's attention heads overlaid on each copy. The overlay is a 4x4 grid of translucent rectangles (one per ViT patch, since 64/16 = 4); each rectangle's color is its incoming attention summed over all query patches and mapped through viridis. The painting tells you which regions of the cat each head decided were worth aggregating evidence from. Compare with the side-by-side heatmap_grid demo above -- that view gives you the [16, 16] matrix per head (every query-to-key pair), but it does NOT tell you where on the image each patch SITS. The overlay does. Common patterns to look for after training: one head fixating on a single bright region (eyes / face / silhouette), one head spreading attention thinly across many patches, two intermediate heads. The architecture says 'four independent attention subspaces'; the overlay shows you what gradient descent decided those subspaces SHOULD pay attention to on this particular cat.",
    lines: &[
        "pets = load_preloaded(\"pets_tiny\")",
        "c0 = reshape(take(pets.X, 0, 0),   [1, 3, 64, 64])",
        "c1 = reshape(take(pets.X, 0, 1),   [1, 3, 64, 64])",
        "c2 = reshape(take(pets.X, 0, 2),   [1, 3, 64, 64])",
        "c3 = reshape(take(pets.X, 0, 3),   [1, 3, 64, 64])",
        "d0 = reshape(take(pets.X, 0, 100), [1, 3, 64, 64])",
        "d1 = reshape(take(pets.X, 0, 101), [1, 3, 64, 64])",
        "d2 = reshape(take(pets.X, 0, 102), [1, 3, 64, 64])",
        "d3 = reshape(take(pets.X, 0, 103), [1, 3, 64, 64])",
        "cats = concat(concat(concat(c0, c1, 0), c2, 0), c3, 0)",
        "dogs = concat(concat(concat(d0, d1, 0), d2, 0), d3, 0)",
        "X    = concat(cats, dogs, 0)",
        "ly0 = reshape(take(pets.Y, 0, 0),   [1])",
        "ly1 = reshape(take(pets.Y, 0, 1),   [1])",
        "ly2 = reshape(take(pets.Y, 0, 2),   [1])",
        "ly3 = reshape(take(pets.Y, 0, 3),   [1])",
        "ld0 = reshape(take(pets.Y, 0, 100), [1])",
        "ld1 = reshape(take(pets.Y, 0, 101), [1])",
        "ld2 = reshape(take(pets.Y, 0, 102), [1])",
        "ld3 = reshape(take(pets.Y, 0, 103), [1])",
        "ycats = concat(concat(concat(ly0, ly1, 0), ly2, 0), ly3, 0)",
        "ydogs = concat(concat(concat(ld0, ld1, 0), ld2, 0), ld3, 0)",
        "Y     = concat(ycats, ydogs, 0)",
        "# Same 4-head architecture as the demo above.",
        "linear_p   = linear(768, 128, 17)",
        "attn       = attention(128, 4, 23)",
        "classifier = chain(linear(128, 64, 31), relu_layer(), linear(64, 2, 37))",
        "train 30 { adam(cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y), [linear_p, attn, classifier], 0.001, 0.9, 0.999, 0.00000001); cross_entropy(apply(classifier, take(apply(attn, reshape(apply(linear_p, reshape(patchify(X, 16), [128, 768])), [8, 16, 128])), 1, 0)), Y) }",
        "loss_curve(last_losses)",
        "# Per-head per-patch attention on the first cat:",
        "# attention_weights -> [4, 16, 16]; reduce over axis 1",
        "# (query patches) and divide by 16 to get [4, 16] mean",
        "# incoming attention per patch per head.",
        "test_img    = reshape(take(pets.X, 0, 0), [1, 3, 64, 64])",
        "test_tokens = reshape(apply(linear_p, reshape(patchify(test_img, 16), [16, 768])), [16, 128])",
        "attn_maps   = attention_weights(attn, test_tokens)",
        "per_head    = reduce_add(attn_maps, 1) / 16",
        "img_for_viz = reshape(test_img, [3, 64, 64])",
        "svg(img_for_viz, \"attention_overlay\", per_head)",
    ],
};
