//! Saga 33 step 001: language-model + tiny-MLP demos
//! extracted from `demos.rs`. Pure compile-time data.

use crate::demos::Demo;

pub const TINY_LM_GENERATE: Demo = Demo {
    name: "Tiny LM Generate",
    intro: "End-to-end tiny transformer language model: tokenize a small corpus with BPE, wrap inputs as next-token pairs, build a 1-layer model (embed + causal_attention + rms_norm + linear head), train 30 [[Adam]] steps, then sample 20 tokens from a prompt and render the attention heatmap. The smallest program that trains and generates text.",
    takeaway: "A language model with a few thousand parameters produced a decoded string from a learned distribution and a [T,T] heatmap of what each position attended to. The loss curve should trend downward; the generated text is noisy because the model and budget are both tiny -- scale V, d, block, and step count for a serious run via the CLI.",
    lines: &[
        "corpus = load_preloaded(\"tiny_corpus\")                                                                                                                                                                                                                                                          # short pangram-style training corpus",
        "tok    = train_bpe(corpus, 260, 0)                                                                                                                                                                                                                                                                # train a 260-token BPE tokenizer",
        "ids    = apply_tokenizer(tok, corpus)                                                                                                                                                                                                                                                              # encode corpus -> integer ids",
        "X_all = shift_pairs_x(ids, 8)                                                                                                                                                                                                                                                                       # next-token input windows of length 8",
        "Y_all = shift_pairs_y(ids, 8)                                                                                                                                                                                                                                                                       # matching target windows shifted by 1",
        "X     = reshape(X_all, [reduce_mul(shape(X_all))])                                                                                                                                                                                                                                                  # flatten to 1-D for the embed lookup",
        "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])                                                                                                                                                                                                                                                  # flatten targets",
        "V = 260 ; d = 16 ; h = 1                                                                                                                                                                                                                                                                            # vocab / embed-dim / heads",
        "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))                                                                                                                                                                                                              # 1-layer transformer LM",
        "experiment \"tiny_lm_gen\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }  # train 30 Adam steps; record per-step loss",
        "loss_curve(last_losses)                                                                                                                                                                                                                                                                             # plot the training loss",
        "perplexity(apply(model, X), Y)                                                                                                                                                                                                                                                                       # exp(CE) -- canonical LM metric (lower is better)",
        "prompt = apply_tokenizer(tok, \"the \")                                                                                                                                                                                                                                                              # seed prompt as token ids",
        "seq    = prompt                                                                                                                                                                                                                                                                                      # generation buffer",
        "repeat 20 { logits = apply(model, seq); last = last_row(logits); nxt = sample(top_k(last, 20), 0.8, step); seq = concat(seq, nxt) }                                                                                                                                                                  # 20-token sample with top-k 20 + temperature 0.8",
        "decode(tok, seq)                                                                                                                                                                                                                                                                                     # decode ids back to text",
        "viz_ids = apply_tokenizer(tok, \"the quick\")                                                                                                                                                                                                                                                          # short input for the heatmap",
        "attn_w  = attention_weights(model, viz_ids)                                                                                                                                                                                                                                                          # extract the [T, T] attention weights",
        "svg(attn_w, \"heatmap\")                                                                                                                                                                                                                                                                              # what each position attended to",
    ],
};

pub const TINY_LM: Demo = Demo {
    name: "Tiny LM",
    intro: "Training-only variant of the Tiny LM: same model shape ([[Embedding]] + [[Attention]] (causal) + RMS norm + linear head, V=260, d=16, block=8), wrapped in [[experiment block (language keyword)]] so the final metric is logged, then plot the loss curve across 30 [[Adam]] steps. No generation -- just a clean 'does the loss go down' demo.",
    takeaway: "Loss curve trends downward over 30 steps; the [[experiment block (language keyword)]] registry records the run's final loss metric. For generation + attention visualization, see 'Tiny LM Generate'. For a serious run with V=280 and 200 steps, use the CLI: `mlpl-repl -f demos/tiny_lm.mlpl`.",
    lines: &[
        "corpus = load_preloaded(\"tiny_corpus\")                                                                                                                                                                                                                                                          # built-in pangram corpus",
        "tok    = train_bpe(corpus, 260, 0)                                                                                                                                                                                                                                                                # train a 260-token BPE tokenizer",
        "ids    = apply_tokenizer(tok, corpus)                                                                                                                                                                                                                                                              # encode the corpus to ids",
        "X_all = shift_pairs_x(ids, 8)                                                                                                                                                                                                                                                                       # next-token input windows of length 8",
        "Y_all = shift_pairs_y(ids, 8)                                                                                                                                                                                                                                                                       # matching target windows shifted by 1",
        "X     = reshape(X_all, [reduce_mul(shape(X_all))])                                                                                                                                                                                                                                                  # flatten to 1-D",
        "Y     = reshape(Y_all, [reduce_mul(shape(Y_all))])                                                                                                                                                                                                                                                  # flatten targets",
        "V = 260 ; d = 16 ; h = 1                                                                                                                                                                                                                                                                            # vocab / embed-dim / heads",
        "model = chain(embed(V, d, 0), causal_attention(d, h, 1), rms_norm(d), linear(d, V, 2))                                                                                                                                                                                                              # 1-layer transformer LM",
        "experiment \"tiny_lm\" { train 30 { adam(cross_entropy(apply(model, X), Y), model, 0.01, 0.9, 0.999, 0.00000001); loss_metric = cross_entropy(apply(model, X), Y) } }  # 30 Adam steps inside an experiment block",
        "loss_curve(last_losses)                                                                                                                                                                                                                                                                             # plot the training loss",
        "perplexity(apply(model, X), Y)                                                                                                                                                                                                                                                                       # exp(CE) -- the canonical LM metric, lower is better",
    ],
};

pub const TINY_MLP: Demo = Demo {
    name: "Tiny MLP",
    intro: "A hand-rolled 2-layer MLP on four blobs (two per class, XOR-ish layout). Forward + backward pass written out explicitly so every gradient is visible -- no autograd, no Model DSL. Ends with the decision-boundary render over a 30x30 grid.",
    takeaway: "You can see every matmul and every elementwise op in the training loop. For the same model with autograd hiding the backward pass, see 'Moons MLP'; for the same model as a Model DSL composition, see the tutorial's 'Model Composition' lesson.",
    lines: &[
        "D = blobs(3, 20, [[-2,-2],[2,2],[-2,2],[2,-2]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # 80 points in four blobs (XOR layout)",
        "X = matmul(D, [[1,0],[0,1],[0,0]])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # drop the label column",
        "raw = reshape(matmul(D, [[0],[0],[1]]), [80])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # raw labels 0..3 (one per quadrant)",
        "y = gt(raw, 1.5)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # binary label: half the quadrants are positive",
        "Y = one_hot(y, 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # one-hot for the loss",
        "W1 = randn(5, [2, 8]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # input -> hidden weights",
        "b1 = zeros([8])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden bias",
        "W2 = randn(6, [8, 2]) * 0.5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # hidden -> output weights",
        "b2 = zeros([2])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # output bias",
        "lr = 0.2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # learning rate",
        "repeat 600 { Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8])); H = tanh_fn(Z1); Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2])); P = softmax(Z2, 1); dZ2 = P - Y; gW2 = matmul(transpose(H), dZ2) / 80; gb2 = reduce_add(dZ2, 0) / 80; dH = matmul(dZ2, transpose(W2)); dZ1 = dH * (1 - H * H); gW1 = matmul(transpose(X), dZ1) / 80; gb1 = reduce_add(dZ1, 0) / 80; W1 = W1 - lr * gW1; b1 = b1 - lr * gb1; W2 = W2 - lr * gW2; b2 = b2 - lr * gb2 }  # 600 hand-rolled forward + backward steps; chain rule visible in dZ1 = dH * (1 - H*H)",
        "Z1 = matmul(X, W1) + matmul(ones([80, 1]), reshape(b1, [1, 8]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # final forward: hidden pre-activation",
        "H = tanh_fn(Z1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # hidden activation",
        "Z2 = matmul(H, W2) + matmul(ones([80, 1]), reshape(b2, [1, 2]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # output pre-activation",
        "P = softmax(Z2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # row-wise probabilities",
        "mlp_pred = argmax(P, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # discrete class predictions",
        "mean(eq(mlp_pred, y))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # accuracy",
        "confusion_matrix(mlp_pred, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 2x2 prediction-vs-actual",
        "G = grid([-4, 4, -4, 4], 30)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # 30x30 input-space grid",
        "GZ1 = matmul(G, W1) + matmul(ones([900, 1]), reshape(b1, [1, 8]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid forward: hidden pre-activation",
        "GH = tanh_fn(GZ1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid hidden activation",
        "GZ2 = matmul(GH, W2) + matmul(ones([900, 1]), reshape(b2, [1, 2]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid output pre-activation",
        "GP = softmax(GZ2, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # grid probabilities",
        "p1 = reshape(matmul(GP, [[0],[1]]), [900])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # extract probability of class 1",
        "boundary_2d(p1, [30, 30], X, y)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # the decision surface that XOR needs",
    ],
};
