pub fn help_text() -> String {
    [
        "MLPL v0.9.0 -- Array Programming Language for ML",
        "",
        "Syntax:",
        "  42 / 1.5            scalar literal",
        "  [1, 2, 3]           array literal",
        "  \"text\"              string literal",
        "  x = expr            assignment",
        "  x : [a, b] = expr   labeled-axis assignment",
        "  a + b               arithmetic (+, -, *, /)",
        "  func(args)          function call",
        "  param[shape]        trainable parameter leaf",
        "  tensor[shape]       non-trainable tape tensor",
        "  repeat N { body }   loop N times",
        "  train N { body }    training loop (binds step, last_losses)",
        "  for row in X { }    iterate rows (binds last_rows)",
        "  experiment \"n\" { }  capture _metric scalars + params",
        "  # comment            to end of line",
        "",
        "Built-in categories (see :help <topic> or :builtins for the",
        "full list):",
        "  core       iota, shape, rank, reshape, transpose,",
        "             reduce_add, reduce_mul, argmax, mean",
        "  labels     label, relabel, reshape_labeled, labels",
        "  linalg     dot, matmul",
        "  math       exp, log, sqrt, abs, pow, sigmoid, tanh_fn",
        "  ctors      zeros, ones, fill, grid, random, randn,",
        "             blobs, moons, circles",
        "  ml         softmax, one_hot, cross_entropy, sample, top_k",
        "  autograd   grad(expr, wrt)",
        "  optim      momentum_sgd, adam, cosine_schedule,",
        "             linear_warmup",
        "  modeldsl   linear, chain, residual, rms_norm, attention,",
        "             causal_attention, embed, sinusoidal_encoding,",
        "             tanh_layer, relu_layer, softmax_layer, apply,",
        "             params",
        "  data       load, load_preloaded, shuffle, batch,",
        "             batch_mask, split, val_split",
        "  tokenize   tokenize_bytes, decode_bytes, train_bpe,",
        "             apply_tokenizer, decode",
        "  lm         shift_pairs_x, shift_pairs_y, last_row, concat,",
        "             attention_weights",
        "  experiment compare",
        "  viz        svg, hist, scatter_labeled, loss_curve,",
        "             confusion_matrix, boundary_2d",
        "",
        "Commands:",
        "  :help                show this help",
        "  :help <topic>        focused help: vars, models, fns,",
        "                       builtins, describe, wsid",
        "  :vars                list bound variables with shape",
        "  :models              list bound models with layer structure",
        "  :fns                 list user-defined functions",
        "  :builtins            list built-in functions by category",
        "  :describe <name>     describe a variable, model, tokenizer,",
        "                       or built-in",
        "  :wsid                workspace summary",
        "  :experiments         list captured experiment runs",
        "  :clear               reset all variables",
    ]
    .join("\n")
}
