number = 1
slug = "upload-demo"
status = "completed"
description = """
Step 001: Upload & Inspect Image demo under Basics.

Create a new demo showin..."""
role = "production"
context_files = []
created_at = "2026-05-27T16:09:01"
completed_at = "2026-05-27T16:11:55"
task_type = "feature"
commits = ["184409b5ee57ef4b2978d47d9e4637e37f2306a3"]
