[workspace]
members = [
    "crates/mlpl-web-render-aux",
    "crates/mlpl-web-render-core",
    "crates/mlpl-web-render-shell",
    "crates/mlpl-web-render-types",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.20.0"

[workspace.lints.clippy]
pedantic = "warn"
