//! Lower every `WORKLOADS` entry through `mlpl-lower-rs` and emit
//! a free `case_<name>() -> DenseArray` function per workload into
//! `$OUT_DIR/compiled_cases.rs`. The Criterion harness `include!`s
//! that file so the bench runs the exact Rust code `mlpl build`
//! would emit, not a hand-written stand-in.

use std::env;
use std::fs;
use std::path::PathBuf;

// Keep this list in sync with `src/lib.rs`. Duplicated here because
// a build-script can't depend on its own crate's lib. Trivially
// small; guarded by the bench-harness assertion that every entry
// has a matching compiled fn.
const WORKLOADS: &[(&str, &str)] = &[
    ("scalar_tight", "1 + 2 * 3 - 4"),
    (
        "small_array_arith",
        "reduce_add([1, 2, 3, 4, 5] * 10 + [0, 1, 2, 3, 4])",
    ),
    ("iota_reduce_100", "reduce_add(iota(100))"),
    (
        "reshape_reduce_100x100",
        "m = reshape(iota(10000), [100, 100]); \
         rows = reduce_add(m, 0); \
         cols = reduce_add(m, 1); \
         reduce_add(rows) + reduce_add(cols)",
    ),
    (
        "matmul_16x16",
        "a = reshape(iota(256), [16, 16]); \
         b = reshape(iota(256) + 1, [16, 16]); \
         reduce_add(matmul(a, b))",
    ),
    (
        "transpose_chain_10x10",
        "m = reshape(iota(100), [10, 10]); \
         reduce_add(transpose(m) + m)",
    ),
];

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("compiled_cases.rs");

    let mut src = String::new();
    src.push_str("// Generated by mlpl-bench build.rs -- do not edit.\n");
    src.push_str("use mlpl_rt::DenseArray;\n\n");
    for (name, body) in WORKLOADS {
        let tokens =
            mlpl_parser::lex(body).unwrap_or_else(|e| panic!("mlpl-bench: lex {name}: {e}"));
        let stmts =
            mlpl_parser::parse(&tokens).unwrap_or_else(|e| panic!("mlpl-bench: parse {name}: {e}"));
        let lowered = mlpl_lower_rs::lower(&stmts)
            .unwrap_or_else(|e| panic!("mlpl-bench: lower {name}: {e:?}"));
        src.push_str(&format!(
            "#[inline(never)]\n#[allow(unused_braces, clippy::all, clippy::pedantic)]\n\
             pub fn case_{name}() -> DenseArray {{\n    {lowered}\n}}\n\n"
        ));
    }

    src.push_str("pub const COMPILED: &[(&str, fn() -> DenseArray)] = &[\n");
    for (name, _) in WORKLOADS {
        src.push_str(&format!("    (\"{name}\", case_{name}),\n"));
    }
    src.push_str("];\n");

    fs::write(&dest, src).expect("writing compiled_cases.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/lib.rs");
}
