[book]
authors = ["MLPL Team"]
language = "en"
src = "src"
title = "MLPL User Guide"

[output.html]
git-repository-url = "https://github.com/sw-ml-study/sw-mlpl"
edit-url-template = "https://github.com/sw-ml-study/sw-mlpl/edit/main/docs/usage.md"

[output.epub]
enabled = true

[output.pdf]
enabled = true
