[package]
name = "mlpl-viz"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
mlpl-viz-core = { path = "../mlpl-viz-core" }
mlpl-viz-marks = { path = "../mlpl-viz-marks" }
mlpl-viz-analysis = { path = "../mlpl-viz-analysis" }
mlpl-viz-flow = { path = "../mlpl-viz-flow" }
mlpl-array = { path = "../../../array/crates/mlpl-array" }
mlpl-core = { path = "../../../types/crates/mlpl-core" }
mlpl-trace = { path = "../../../autograd/crates/mlpl-trace" }
