//! Elementwise op methods on [`Tensor`].
//!
//! Method implementations are generated by the [`unary_method!`] and
//! [`binary_method!`] macros to keep the per-file function count low
//! while still giving ergonomic `tensor.add(&other)` / `tensor.exp()`
//! call sites.

use std::rc::Rc;

use crate::tensor::Tensor;
use mlpl_autograd_tape::{BinaryOp, UnaryOp};
use mlpl_autograd_tape::{NodeData, NodeKind, ResidentReq, map_unary, try_resident};
use mlpl_tensor_handle::TensorHandle;

pub(crate) fn push_unary(t: &Tensor, op: UnaryOp) -> Tensor {
    // Ops without a device kernel (e.g. sin/cos) run on the host path.
    let dev = map_unary(op).and_then(|k| try_resident(&t.tape, ResidentReq::Unary(t.node, k)));
    let value = dev.unwrap_or_else(|| {
        if t.tape.resident.get() {
            mlpl_tensor_handle::bump(mlpl_tensor_handle::SeamEvent::CpuFallback);
        }
        TensorHandle::Cpu(op.forward(&t.value()))
    });
    let node = t.tape.push(NodeData {
        value,
        grad: None,
        kind: NodeKind::Unary { op, parent: t.node },
        requires_grad: false,
    });
    Tensor {
        node,
        tape: Rc::clone(&t.tape),
    }
}

pub(crate) fn push_binary(a: &Tensor, b: &Tensor, op: BinaryOp) -> Tensor {
    let dev = try_resident(
        &a.tape,
        ResidentReq::Binary(a.node, b.node, mlpl_autograd_tape::map_binary(op)),
    );
    let value = dev.unwrap_or_else(|| {
        TensorHandle::Cpu(
            op.forward(&a.value(), &b.value())
                .expect("broadcastable shapes"),
        )
    });
    let node = a.tape.push(NodeData {
        value,
        grad: None,
        kind: NodeKind::Binary {
            op,
            left: a.node,
            right: b.node,
        },
        requires_grad: false,
    });
    Tensor {
        node,
        tape: Rc::clone(&a.tape),
    }
}

macro_rules! unary_method {
    ($name:ident, $variant:ident, $doc:expr) => {
        #[doc = $doc]
        #[must_use]
        pub fn $name(&self) -> Self {
            $crate::tensor_ops::push_unary(self, $crate::ops::UnaryOp::$variant)
        }
    };
}

macro_rules! binary_method {
    ($name:ident, $variant:ident, $doc:expr) => {
        #[doc = $doc]
        #[must_use]
        pub fn $name(&self, other: &Self) -> Self {
            $crate::tensor_ops::push_binary(self, other, $crate::ops::BinaryOp::$variant)
        }
    };
}

impl Tensor {
    binary_method!(add, Add, "Elementwise addition.");
    binary_method!(sub, Sub, "Elementwise subtraction.");
    binary_method!(mul, Mul, "Elementwise multiplication.");
    binary_method!(div, Div, "Elementwise division.");

    unary_method!(neg, Neg, "Elementwise negation.");
    unary_method!(exp, Exp, "Elementwise exponential.");
    unary_method!(log, Log, "Elementwise natural log.");
    unary_method!(relu, Relu, "Elementwise ReLU.");
    unary_method!(tanh, Tanh, "Elementwise tanh.");
    unary_method!(sigmoid, Sigmoid, "Elementwise sigmoid.");
    unary_method!(sqrt, Sqrt, "Elementwise square root.");
    unary_method!(sin, Sin, "Elementwise sine.");
    unary_method!(cos, Cos, "Elementwise cosine.");

    /// Fused cross-entropy loss (Saga 13 step 004).
    ///
    /// `targets` is consumed and stored verbatim on the tape node: it
    /// carries class indices (no gradient flows through it). Caller
    /// guarantees `0 <= targets[i] < V` for every row, where `V` is
    /// the trailing axis of `self`'s logits.
    #[must_use]
    pub fn cross_entropy(&self, targets: Vec<usize>) -> Self {
        let value =
            try_resident(&self.tape, ResidentReq::Ce(self.node, &targets)).unwrap_or_else(|| {
                TensorHandle::Cpu(
                    mlpl_autograd_backward::cross_entropy_forward(&self.value(), &targets)
                        .expect("caller validated shapes and indices"),
                )
            });
        let node = self.tape.push(NodeData {
            value,
            grad: None,
            kind: NodeKind::CrossEntropy {
                logits: self.node,
                targets,
            },
            requires_grad: false,
        });
        Tensor {
            node,
            tape: Rc::clone(&self.tape),
        }
    }
}
