[package]
name = "mlpl-build"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "mlpl-build"
path = "src/main.rs"

[dependencies]
mlpl-lower-rs = { path = "../../../syntax-codegen/crates/mlpl-lower-rs" }
mlpl-array-ops-matmul = { path = "../../../array-compose/crates/mlpl-array-ops-matmul" }
mlpl-parser = { path = "../../../syntax-parser/crates/mlpl-parser" }
mlpl-parser-ast = { path = "../../../syntax-parser/crates/mlpl-parser-ast" }
mlpl-source-loader = { path = "../../../syntax-parser/crates/mlpl-source-loader" }
quote = "1"
