[package]
name = "mlpl-array"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
mlpl-core = { path = "../../../types/crates/mlpl-core" }

[dev-dependencies]
mlpl-array-ops-matmul = { path = "../../../array-compose/crates/mlpl-array-ops-matmul" }
mlpl-array-ops-reduce = { path = "../../../array-compose/crates/mlpl-array-ops-reduce" }
mlpl-array-ops-compose = { path = "../../../array-compose/crates/mlpl-array-ops-compose" }
mlpl-array-ops-shape = { path = "../../../array-element/crates/mlpl-array-ops-shape" }
mlpl-array-ops-element = { path = "../../../array-element/crates/mlpl-array-ops-element" }
