//! Elementwise op methods on [`Tensor`].
//!
//! Method implementations are generated by the [`unary_method!`] and
//! [`binary_method!`] macros to keep the per-file function count low
//! while still giving ergonomic `tensor.add(&other)` / `tensor.exp()`
//! call sites.

use std::rc::Rc;

use crate::ops::{BinaryOp, UnaryOp};
use crate::tape::{NodeData, NodeKind};
use crate::tensor::Tensor;

pub(crate) fn push_unary(t: &Tensor, op: UnaryOp) -> Tensor {
    let x = t.value();
    let y = op.forward(&x);
    let node = t.tape.push(NodeData {
        value: y,
        grad: None,
        kind: NodeKind::Unary { op, parent: t.node },
        requires_grad: false,
    });
    Tensor {
        node,
        tape: Rc::clone(&t.tape),
    }
}

pub(crate) fn push_binary(a: &Tensor, b: &Tensor, op: BinaryOp) -> Tensor {
    let av = a.value();
    let bv = b.value();
    let v = op.forward(&av, &bv).expect("broadcastable shapes");
    let node = a.tape.push(NodeData {
        value: v,
        grad: None,
        kind: NodeKind::Binary {
            op,
            left: a.node,
            right: b.node,
        },
        requires_grad: false,
    });
    Tensor {
        node,
        tape: Rc::clone(&a.tape),
    }
}

macro_rules! unary_method {
    ($name:ident, $variant:ident, $doc:expr) => {
        #[doc = $doc]
        #[must_use]
        pub fn $name(&self) -> Self {
            $crate::tensor_ops::push_unary(self, $crate::ops::UnaryOp::$variant)
        }
    };
}

macro_rules! binary_method {
    ($name:ident, $variant:ident, $doc:expr) => {
        #[doc = $doc]
        #[must_use]
        pub fn $name(&self, other: &Self) -> Self {
            $crate::tensor_ops::push_binary(self, other, $crate::ops::BinaryOp::$variant)
        }
    };
}

impl Tensor {
    binary_method!(add, Add, "Elementwise addition.");
    binary_method!(sub, Sub, "Elementwise subtraction.");
    binary_method!(mul, Mul, "Elementwise multiplication.");
    binary_method!(div, Div, "Elementwise division.");

    unary_method!(neg, Neg, "Elementwise negation.");
    unary_method!(exp, Exp, "Elementwise exponential.");
    unary_method!(log, Log, "Elementwise natural log.");
    unary_method!(relu, Relu, "Elementwise ReLU.");
    unary_method!(tanh, Tanh, "Elementwise tanh.");
    unary_method!(sigmoid, Sigmoid, "Elementwise sigmoid.");
}
