//! Tutorial-lesson static content for the web playground. Leaf crate.
//!
//! - `lessons`: the `Lesson` type + the `LESSONS` array, generated by
//!   `build.rs` from `lessons.toml` (the content lives in data, not source).
//! - `intro_md`: the tutorial-intro markdown-to-html renderer (`render`).

pub mod intro_md;
pub mod lessons;

pub use lessons::{LESSONS, Lesson};
