[package]
name = "mlpl-wasm"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mlpl-array = { path = "../../../array/crates/mlpl-array" }
mlpl-eval = { path = "../../../eval/crates/mlpl-eval" }
mlpl-parser = { path = "../../../syntax-parser/crates/mlpl-parser" }
mlpl-trace = { path = "../../../autograd/crates/mlpl-trace" }
mlpl-web-viz-ir = { path = "../../../web-viz-ir/crates/mlpl-web-viz-ir" }
mlpl-model-viz = { path = "../../../web-viz-ir/crates/mlpl-model-viz" }
wasm-bindgen = "0.2"
