[package]
name = "mlpl-wasm"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mlpl-array = { path = "../../components/lang-core/crates/mlpl-array" }
mlpl-eval = { path = "../mlpl-eval" }
mlpl-parser = { path = "../../components/lang-syntax/crates/mlpl-parser" }
mlpl-trace = { path = "../../components/autograd/crates/mlpl-trace" }
wasm-bindgen = "0.2"
