[package]
name = "mlpl-runtime-rnn"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
mlpl-array = { path = "../../../lang-core/crates/mlpl-array" }
mlpl-array-ops-element = { path = "../../../lang-core/crates/mlpl-array-ops-element" }
mlpl-array-ops-matmul = { path = "../../../lang-core/crates/mlpl-array-ops-matmul" }
mlpl-runtime-core = { path = "../../../runtime-core/crates/mlpl-runtime-core" }
